AddCSLuaFile()

SWEP.UseHands = true
SWEP.ViewModel = Model("models/sg/weapons/sunrust/c_m4a1.mdl")
SWEP.WorldModel = Model("models/weapons/w_rif_m4a1.mdl")

SWEP.ViewModelAttachments = {
	Muzzle = {
		Attachment = "1"
	}
}

SWEP.WorldModelAttachments = {
	Muzzle = {
		Attachment = "muzzle"
	}
}

if SERVER then
	return
end

SWEP.ViewModelFOV = 54
SWEP.ViewModelFlip = false
SWEP.ViewModelOffset = Vector(2, 2, 2.5)

SWEP.ShowViewModel = false
SWEP.ShowWorldModel = false

SWEP.VElements = {
	["back"] = { type = "Model", model = "models/props_lab/scrapyarddumpster_static.mdl", bone = "gun", rel = "receiver", pos = Vector(-0.03, -4.35, -1.08), angle = Angle(0, 90, 0), size = Vector(0.02, 0.012, 0.023), color = Color(153, 151, 151, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["back engine"] = { type = "Model", model = "models/vehicle/vehicle_engine_block.mdl", bone = "gun", rel = "receiver", pos = Vector(0, -4.547, 0.61), angle = Angle(-42, 90, 0), size = Vector(0.047, 0.047, 0.047), color = Color(172, 135, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_canal/mattpipe.mdl", bone = "gun", rel = "receiver", pos = Vector(0, 19.216, 0.256), angle = Angle(-90, -90, 0), size = Vector(0.5, 0.5, 0.4), color = Color(180, 180, 180, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal4", skin = 0, bodygroup = {} },
	["barrel c1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "barrel", pos = Vector(-0.912, -2.656, -5.6), angle = Angle(0, 0, 0)},
	["body detail"] = { type = "Model", model = "models/props_c17/trappropeller_engine.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "receiver", pos = Vector(-0.23, -1.697, -0.15), angle = Angle(-90, 90, 0), size = Vector(0.1, 0.1, 0.163), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "gun", rel = "receiver", pos = Vector(0.79, -6.5, 0.08), angle = Angle(-90, 0, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing+"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "gun", rel = "receiver", pos = Vector(0.79, -7.1, 0.08), angle = Angle(-90, 81.724, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing++"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "gun", rel = "receiver", pos = Vector(0.79, -7.7, 0.08), angle = Angle(-90, 38.705, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing+++"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "gun", rel = "receiver", pos = Vector(0.79, -8.3, 0.08), angle = Angle(-90, 177.95, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["center"] = { type = "Model", model = "models/hunter/blocks/cube025x025x025.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "receiver", pos = Vector(0, 9.024, -1.488), angle = Angle(0, 90, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 0), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["chargehandle"] = { type = "Model", model = "models/props_mining/diesel_generator_crank.mdl", bone = "charging_handle", rel = "", pos = Vector(0.262, 0.588, 2.72), angle = Angle(-180, 30, 0), size = Vector(0.1, 0.1, 0.1), color = Color(191, 145, 97, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["front grip"] = { type = "Model", model = "models/props/de_train/biohazardtank_dm_10.mdl", bone = "gun", rel = "receiver", pos = Vector(4.416, 6.896, -6.976), angle = Angle(0, -90, 0), size = Vector(0.2, 0.09, 0.09), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/wood1", skin = 0, bodygroup = {} },
	["grip"] = { type = "Model", model = "models/sg/weapons/sunrust/c_m4a1.mdl", bone = "gun", rel = "receiver", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(1, 1, 1), color = Color(233, 202, 167, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["grip c1"] = { type = "ClipPlane", bone = "gun", rel = "grip", pos = Vector(0, -0.99, -0.9), angle = Angle(180, 0, 0)},
	["grip c2"] = { type = "ClipPlane", bone = "gun", rel = "grip", pos = Vector(0, -2.42, -0.15), angle = Angle(180, 0, 25.868)},
	["holder"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "gun", rel = "casing", pos = Vector(0.46, 0, -0.06), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["holder+"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "gun", rel = "casing+", pos = Vector(0.46, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["holder++"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "gun", rel = "casing++", pos = Vector(0.46, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["holder+++"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "gun", rel = "casing+++", pos = Vector(0.46, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["receiver"] = { type = "Model", model = "models/props_wasteland/cargo_container01.mdl", bone = "gun", rel = "", pos = Vector(0, -0.15, -0.12), angle = Angle(0, 0, -90), size = Vector(0.011, 0.02, 0.02), color = Color(161, 134, 117, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 1, bodygroup = {} },
	["scope"] = { type = "Model", model = "models/props_junk/glassbottle01a.mdl", bone = "gun", rel = "receiver", pos = Vector(0.04, 0, 2.75), angle = Angle(112, 0, 90), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/props/glassbottle", skin = 1, bodygroup = {} },
	["side detail"] = { type = "Model", model = "models/props_trainstation/wrecked_boxcar_gate_door.mdl", bone = "gun", rel = "receiver", pos = Vector(0.83, 1.8, -1.09), angle = Angle(0, 0, -90), size = Vector(0.023, 0.027, 0.023), color = Color(93, 93, 93, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight base"] = { type = "Model", model = "models/Items/item_item_crate.mdl", bone = "gun", rel = "receiver", pos = Vector(0, -0.7, 2.02), angle = Angle(0, -90, 180), size = Vector(0.06, 0.021, 0.033), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock"] = { type = "Model", model = "models/weapons/cstrike/c_shot_m3super90.mdl", bone = "gun", rel = "receiver", pos = Vector(7.681, -17.081, 5.213), angle = Angle(-5, -90, 0), size = Vector(1, 1, 0.76), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = true, material = "models/sg/wood/wood1", skin = 0, bodygroup = {} },
	["stock c1"] = { type = "ClipPlane", bone = "gun", rel = "stock", pos = Vector(12.896, 3.244, -5.826), angle = Angle(73.293, 0, 0)},
	["stock c2"] = { type = "ClipPlane", bone = "gun", rel = "stock", pos = Vector(15.396, 4.318, -8.399), angle = Angle(0, 0, 0)},
	["top"] = { type = "Model", model = "models/props/de_train/flatcar.mdl", bone = "gun", rel = "receiver", pos = Vector(0, 0, 0.688), angle = Angle(0, 90, 0), size = Vector(0.011, 0.012, 0.012), color = Color(102, 94, 87, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["top rail"] = { type = "Model", model = "models/props_junk/trashdumpster01a.mdl", bone = "gun", rel = "receiver", pos = Vector(0.024, 0.041, 0.48), angle = Angle(0, 0, 0), size = Vector(0.02, 0.1, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.WElements = {
	["back"] = { type = "Model", model = "models/props_lab/scrapyarddumpster_static.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(-0.03, -4.35, -1.08), angle = Angle(0, 90, 0), size = Vector(0.02, 0.012, 0.023), color = Color(153, 151, 151, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["back engine"] = { type = "Model", model = "models/vehicle/vehicle_engine_block.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0, -4.547, 0.61), angle = Angle(-42, 90, 0), size = Vector(0.047, 0.047, 0.047), color = Color(172, 135, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_canal/mattpipe.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0, 19.216, 0.256), angle = Angle(-90, -90, 0), size = Vector(0.5, 0.5, 0.4), color = Color(180, 180, 180, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal4", skin = 0, bodygroup = {} },
	["barrel c1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(-0.912, -2.656, -5.6), angle = Angle(0, 0, 0)},
	["body detail"] = { type = "Model", model = "models/props_c17/trappropeller_engine.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(-0.23, -1.697, -0.15), angle = Angle(-90, 90, 0), size = Vector(0.1, 0.1, 0.163), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.79, -6.5, 0.08), angle = Angle(-90, 0, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing+"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.79, -7.1, 0.08), angle = Angle(-90, 81.724, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing++"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.79, -7.7, 0.08), angle = Angle(-90, 38.705, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["casing+++"] = { type = "Model", model = "models/shells/shell_556.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.79, -8.3, 0.08), angle = Angle(-90, 177.95, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["center"] = { type = "Model", model = "models/hunter/blocks/cube025x025x025.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0, 9.024, -1.488), angle = Angle(0, 90, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 0), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["chargehandle"] = { type = "Model", model = "models/props_mining/diesel_generator_crank.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.283, -0.522, 0.04), angle = Angle(-30, -180, 90), size = Vector(0.1, 0.1, 0.1), color = Color(191, 145, 97, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["front grip"] = { type = "Model", model = "models/props/de_train/biohazardtank_dm_10.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(4.416, 6.896, -6.976), angle = Angle(0, -90, 0), size = Vector(0.2, 0.09, 0.09), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/wood1", skin = 0, bodygroup = {} },
	["grip"] = { type = "Model", model = "models/weapons/w_rif_m4a1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(1, 1, 1), color = Color(233, 202, 167, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["grip c1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(-0.39, -7.953, -2.727), angle = Angle(36.647, -90.305, 180)},
	["grip c1+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(-1.422, -8.281, 1.142), angle = Angle(-10.778, -90.305, 180)},
	["holder"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "casing", pos = Vector(0.46, 0, -0.06), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["holder+"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "casing+", pos = Vector(0.46, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["holder++"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "casing++", pos = Vector(0.46, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["holder+++"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "casing+++", pos = Vector(0.46, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalfloor005a", skin = 0, bodygroup = {} },
	["receiver"] = { type = "Model", model = "models/props_wasteland/cargo_container01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(7.7, 0.7, -3.8), angle = Angle(180, 89.7, -10), size = Vector(0.011, 0.02, 0.02), color = Color(161, 134, 117, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 1, bodygroup = {} },
	["scope"] = { type = "Model", model = "models/props_junk/glassbottle01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.04, 0, 2.75), angle = Angle(68, -180, -90), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/props/glassbottle", skin = 1, bodygroup = {} },
	["side detail"] = { type = "Model", model = "models/props_trainstation/wrecked_boxcar_gate_door.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.83, 1.8, -1.09), angle = Angle(0, 0, -90), size = Vector(0.023, 0.027, 0.023), color = Color(93, 93, 93, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight base"] = { type = "Model", model = "models/Items/item_item_crate.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0, -0.7, 2.02), angle = Angle(0, -90, 180), size = Vector(0.06, 0.021, 0.033), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock"] = { type = "Model", model = "models/weapons/w_shot_m3super90.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(-0.04, 5.817, -5.742), angle = Angle(-5, -90, 0), size = Vector(1, 0.85, 0.7), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = true, material = "models/sg/wood/wood1", skin = 0, bodygroup = {} },
	["stock c1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "stock", pos = Vector(-13.018, 5.174, 1.099), angle = Angle(47.425, 0, 0)},
	["top"] = { type = "Model", model = "models/props/de_train/flatcar.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0, 0, 0.688), angle = Angle(0, 90, 0), size = Vector(0.011, 0.012, 0.012), color = Color(102, 94, 87, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["top rail"] = { type = "Model", model = "models/props_junk/trashdumpster01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "receiver", pos = Vector(0.024, 0.041, 0.48), angle = Angle(0, 0, 0), size = Vector(0.02, 0.1, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.ViewModelBoneMods = {}
