AddCSLuaFile()

SWEP.UseHands = true
SWEP.ViewModel = Model("models/weapons/c_357.mdl")
SWEP.WorldModel = Model("models/weapons/w_357.mdl")

if SERVER then
	return
end

SWEP.ViewModelFOV = 54
SWEP.ViewModelFlip = false

SWEP.ShowViewModel = false
SWEP.ShowWorldModel = false
SWEP.ViewModelOffset = Vector(0, 0, -1)

SWEP.VElements = {
	["Body"] = { type = "Model", model = "models/weapons/c_357.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "", pos = Vector(0.322, -0.922, 2.592), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["Body clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "Body", pos = Vector(12.846, -29.326, -2.735), angle = Angle(0, -12, 90)},
	["Lens 1"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "Python", rel = "scope view", pos = Vector(0.5, 0, 0), angle = Angle(0, 90, 90), size = Vector(0.06, 0.06, 0.09), color = Color(255, 57, 57, 254), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["Lens 1+"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "Python", rel = "scope view+", pos = Vector(0.49, -0.003, 0.001), angle = Angle(-90, 0, 0), size = Vector(0.06, 0.06, 0.09), color = Color(255, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["RAIL"] = { type = "Model", model = "models/props_interiors/Radiator01a.mdl", bone = "Python", rel = "top frame", pos = Vector(0, 0, 0.6), angle = Angle(0, 0, 90), size = Vector(0.02, 0.056, 0.015), color = Color(55, 55, 55, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["SHROUD CONNECT"] = { type = "Model", model = "models/props_junk/TrashDumpster01a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "barrel", pos = Vector(1, 0, 1.09), angle = Angle(0, 90, -180), size = Vector(0.01, 0.1, 0.016), color = Color(96, 97, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["SHROUD CONNECT Clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "SHROUD CONNECT", pos = Vector(0, 0, 0), angle = Angle(0, 0, 90)},
	["Sight holder 1"] = { type = "Model", model = "models/props_wasteland/panel_leverHandle001a.mdl", bone = "Python", rel = "sight base", pos = Vector(-0.009, 0.094, 0.165), angle = Angle(0, 90, 0), size = Vector(0.11, 0.11, 0.11), color = Color(165, 165, 165, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["Sight holder 1+"] = { type = "Model", model = "models/props_wasteland/panel_leverHandle001a.mdl", bone = "Python", rel = "sight base+", pos = Vector(-0.009, 0.094, 0.165), angle = Angle(0, 90, 0), size = Vector(0.11, 0.11, 0.11), color = Color(165, 165, 165, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_phx/misc/iron_beam1.mdl", bone = "Python", rel = "", pos = Vector(0.019, -0.176, 5.162), angle = Angle(90, 0, -90), size = Vector(0.165, 0.11, 0.14), color = Color(182, 182, 182, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel shroud"] = { type = "Model", model = "models/props_combine/CombineThumper002.mdl", bone = "Python", rel = "barrel", pos = Vector(12.61, -0.455, 1.599), angle = Angle(0, -90, 90), size = Vector(0.04, 0.03, 0.065), color = Color(136, 136, 136, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel shroud clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "barrel shroud", pos = Vector(1.315, -0.641, 7.948), angle = Angle(0, 0, -30.18)},
	["cyl"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "Cylinder", rel = "", pos = Vector(0, 0, -0.21), angle = Angle(180, 0, 0), size = Vector(0.044, 0.044, 0.05), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/props/rubberfloor004a", skin = 0, bodygroup = {} },
	["emitter BEAM"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter BEAM+", pos = Vector(0.35, -0.001, 0), angle = Angle(0, 0, 0), size = Vector(0.01, 0.08, 0.08), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter BEAM+"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter length", pos = Vector(0.016, 0, 1.354), angle = Angle(90, 0, 0), size = Vector(0.08, 0.08, 0.08), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter adjust"] = { type = "Model", model = "models/Mechanics/gears2/gear_48t3.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter base", pos = Vector(0.326, 0.001, 0.214), angle = Angle(90, 0, 0), size = Vector(0.01, 0.01, 0.01), color = Color(65, 65, 65, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter base"] = { type = "Model", model = "models/props_wasteland/light_spotlight01_lamp.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter connect", pos = Vector(-0.01, -1.127, 0.428), angle = Angle(0, -90, -180), size = Vector(0.05, 0.05, 0.05), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["emitter connect"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "Python", rel = "under front", pos = Vector(0.029, 2.38, -0.899), angle = Angle(0, 0, 0), size = Vector(0.05, 0.067, 0.072), color = Color(99, 86, 86, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter length"] = { type = "Model", model = "models/props_silo/rocket_stage3.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter adjust", pos = Vector(-0.02, 0.002, -0.002), angle = Angle(0, 0, 180), size = Vector(0.005, 0.005, 0.005), color = Color(70, 70, 70, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["scope adjust top"] = { type = "Model", model = "models/props_lab/jar01b.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "scope view link", pos = Vector(0, 0, 0.21), angle = Angle(0, 0, 180), size = Vector(0.13, 0.13, 0.15), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["scope adjust top clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "scope adjust top", pos = Vector(0.621, 0.134, 0.596), angle = Angle(0, 0, 0)},
	["scope view"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Sight holder 1", pos = Vector(1.76, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.013, 0.013, 0.013), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view adjust"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "Python", rel = "scope view connect", pos = Vector(-0.04, 0, -0.07), angle = Angle(0, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view adjust+"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "Python", rel = "scope view connect+", pos = Vector(-0.04, 0, -0.07), angle = Angle(0, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view connect"] = { type = "Model", model = "models/props_junk/terracotta01.mdl", bone = "Python", rel = "scope view", pos = Vector(-1.36, 0, -0.05), angle = Angle(-90, 0, 0), size = Vector(0.059, 0.059, 0.059), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view connect+"] = { type = "Model", model = "models/props_junk/terracotta01.mdl", bone = "Python", rel = "scope view+", pos = Vector(-1.36, 0, -0.05), angle = Angle(-90, 0, 0), size = Vector(0.059, 0.059, 0.059), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view length"] = { type = "Model", model = "models/hunter/tubes/tube1x1x2.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "scope view adjust", pos = Vector(0, 0, -1.5), angle = Angle(0, 0, 0), size = Vector(0.015, 0.015, 0.015), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "METAL6", skin = 0, bodygroup = {} },
	["scope view length+"] = { type = "Model", model = "models/hunter/tubes/tube1x1x2.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "scope view adjust+", pos = Vector(0, 0, -1.5), angle = Angle(0, 0, 0), size = Vector(0.015, 0.015, 0.015), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "METAL6", skin = 0, bodygroup = {} },
	["scope view link"] = { type = "Model", model = "models/hunter/tubes/tube2x2xt.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "scope view length", pos = Vector(0, 0, -0.15), angle = Angle(0, -90, 90), size = Vector(0.008, 0.008, 0.008), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "Metal6", skin = 0, bodygroup = {} },
	["scope view+"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Sight holder 1+", pos = Vector(1.76, 0.017, 0), angle = Angle(0, 0, 0), size = Vector(0.013, 0.013, 0.013), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["shroud clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "barrel shroud", pos = Vector(1.267, -3.605, 12.718), angle = Angle(0, 0, 143.47301)},
	["sight base"] = { type = "Model", model = "models/props_vehicles/mining_car.mdl", bone = "Python", rel = "RAIL", pos = Vector(1.155, 0.5, 0.004), angle = Angle(90, 0, 0), size = Vector(0.015, 0.017, 0.02), color = Color(54, 54, 54, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/dome", skin = 0, bodygroup = {} },
	["sight base clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "sight base", pos = Vector(0.002, -0.082, 0.747), angle = Angle(0, 0, 0)},
	["sight base clip+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "sight base+", pos = Vector(0.002, -0.082, 0.747), angle = Angle(0, 0, 0)},
	["sight base+"] = { type = "Model", model = "models/props_vehicles/mining_car.mdl", bone = "Python", rel = "RAIL", pos = Vector(1.155, 3.2, 0.004), angle = Angle(-90, 0, 180), size = Vector(0.015, 0.017, 0.02), color = Color(55, 55, 55, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/dome", skin = 0, bodygroup = {} },
	["silencer"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "Python", rel = "barrel", pos = Vector(6.619, -0.053, 0.816), angle = Angle(180, -90, 90), size = Vector(0.17, 0.17, 0.17), color = Color(91, 91, 91, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	--["silencer hole"] = { type = "Model", model = "", bone = "ValveBiped.Bip01_Spine4", rel = "silencer", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["top frame"] = { type = "Model", model = "models/props_citizen_tech/firetrap_buttonpad.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "barrel", pos = Vector(-4.3, -0.002, 1.504), angle = Angle(90, 0, 0), size = Vector(0.08, 0.104, 0.31), color = Color(76, 76, 76, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["under back"] = { type = "Model", model = "models/props_c17/display_cooler01a.mdl", bone = "Python", rel = "barrel", pos = Vector(-2.59, 0, 0.23), angle = Angle(180, -90, 0), size = Vector(0.007, 0.05, 0.027), color = Color(252, 236, 236, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/props_silo/pipesa_bombsite", skin = 0, bodygroup = {} },
	["under front"] = { type = "Model", model = "models/Items/item_item_crate.mdl", bone = "Python", rel = "barrel", pos = Vector(0, 0.024, -0.883), angle = Angle(0, 90, 0), size = Vector(0.022, 0.22, 0.039), color = Color(105, 105, 106, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalwall076a", skin = 0, bodygroup = {} }
}

SWEP.WElements = {
	["Body"] = { type = "Model", model = "models/weapons/w_357.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(0.322, -0.922, 2.592), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["Body clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(8.425, -28.039, -2.766), angle = Angle(90, 0, 0)},
	["Lens 1"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view", pos = Vector(0.5, 0, 0), angle = Angle(0, 90, 90), size = Vector(0.06, 0.06, 0.09), color = Color(255, 57, 57, 254), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["Lens 1+"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view+", pos = Vector(0.49, -0.003, 0.001), angle = Angle(-90, 0, 0), size = Vector(0.06, 0.06, 0.09), color = Color(255, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["RAIL"] = { type = "Model", model = "models/props_interiors/Radiator01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "top frame", pos = Vector(0, 0, 0.6), angle = Angle(0, 0, 90), size = Vector(0.02, 0.056, 0.015), color = Color(55, 55, 55, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["SHROUD CONNECT"] = { type = "Model", model = "models/props_junk/TrashDumpster01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(1, 0, 1.09), angle = Angle(0, 90, -180), size = Vector(0.01, 0.1, 0.016), color = Color(96, 97, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["SHROUD CONNECT Clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "SHROUD CONNECT", pos = Vector(0, 0, 0), angle = Angle(0, 0, 90)},
	["Sight holder 1"] = { type = "Model", model = "models/props_wasteland/panel_leverHandle001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight base", pos = Vector(-0.009, 0.094, 0.165), angle = Angle(0, 90, 0), size = Vector(0.11, 0.11, 0.11), color = Color(165, 165, 165, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["Sight holder 1+"] = { type = "Model", model = "models/props_wasteland/panel_leverHandle001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight base+", pos = Vector(-0.009, 0.094, 0.165), angle = Angle(0, 90, 0), size = Vector(0.11, 0.11, 0.11), color = Color(165, 165, 165, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_phx/misc/iron_beam1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(11.594, 1.837, -6.565), angle = Angle(-4, 0, 180), size = Vector(0.165, 0.11, 0.14), color = Color(182, 182, 182, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel shroud"] = { type = "Model", model = "models/props_combine/CombineThumper002.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(12.61, -0.455, 1.599), angle = Angle(0, -90, 90), size = Vector(0.04, 0.03, 0.065), color = Color(136, 136, 136, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel shroud clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel shroud", pos = Vector(1.315, -0.641, 7.948), angle = Angle(0, 0, -30.18)},
	["cyl"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(6.907, 0.941, -3.696), angle = Angle(86.038, 0, 0), size = Vector(0.052, 0.052, 0.052), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/props/rubberfloor004a", skin = 0, bodygroup = {} },
	["emitter BEAM"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter BEAM+", pos = Vector(0.35, -0.001, 0), angle = Angle(0, 0, 0), size = Vector(0.01, 0.08, 0.08), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter BEAM+"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter length", pos = Vector(0.016, 0, 1.354), angle = Angle(90, 0, 0), size = Vector(0.08, 0.08, 0.08), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter adjust"] = { type = "Model", model = "models/Mechanics/gears2/gear_48t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter base", pos = Vector(0.326, 0.001, 0.214), angle = Angle(90, 0, 0), size = Vector(0.01, 0.01, 0.01), color = Color(65, 65, 65, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter base"] = { type = "Model", model = "models/props_wasteland/light_spotlight01_lamp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter connect", pos = Vector(-0.01, -1.127, 0.428), angle = Angle(0, -90, -180), size = Vector(0.05, 0.05, 0.05), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["emitter connect"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "under front", pos = Vector(0.029, 2.38, -0.899), angle = Angle(0, 0, 0), size = Vector(0.05, 0.067, 0.072), color = Color(99, 86, 86, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter length"] = { type = "Model", model = "models/props_silo/rocket_stage3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter adjust", pos = Vector(-0.02, 0.002, -0.002), angle = Angle(0, 0, 180), size = Vector(0.005, 0.005, 0.005), color = Color(70, 70, 70, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["scope adjust top"] = { type = "Model", model = "models/props_lab/jar01b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view link", pos = Vector(0, 0, 0.21), angle = Angle(0, 0, 180), size = Vector(0.13, 0.13, 0.15), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["scope adjust top clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "scope adjust top", pos = Vector(0.621, 0.134, 0.596), angle = Angle(0, 0, 0)},
	["scope view"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Sight holder 1", pos = Vector(1.76, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.013, 0.013, 0.013), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view adjust"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view connect", pos = Vector(-0.04, 0, -0.07), angle = Angle(0, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view adjust+"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view connect+", pos = Vector(-0.04, 0, -0.07), angle = Angle(0, 0, 0), size = Vector(0.006, 0.006, 0.006), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view connect"] = { type = "Model", model = "models/props_junk/terracotta01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view", pos = Vector(-1.36, 0, -0.05), angle = Angle(-90, 0, 0), size = Vector(0.059, 0.059, 0.059), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view connect+"] = { type = "Model", model = "models/props_junk/terracotta01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view+", pos = Vector(-1.36, 0, -0.05), angle = Angle(-90, 0, 0), size = Vector(0.059, 0.059, 0.059), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["scope view length"] = { type = "Model", model = "models/hunter/tubes/tube1x1x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view adjust", pos = Vector(0, 0, -1.5), angle = Angle(0, 0, 0), size = Vector(0.015, 0.015, 0.015), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "METAL6", skin = 0, bodygroup = {} },
	["scope view length+"] = { type = "Model", model = "models/hunter/tubes/tube1x1x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view adjust+", pos = Vector(0, 0, -1.5), angle = Angle(0, 0, 0), size = Vector(0.015, 0.015, 0.015), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "METAL6", skin = 0, bodygroup = {} },
	["scope view link"] = { type = "Model", model = "models/hunter/tubes/tube2x2xt.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view length", pos = Vector(0, 0, -0.15), angle = Angle(0, -90, 90), size = Vector(0.008, 0.008, 0.008), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "Metal6", skin = 0, bodygroup = {} },
	["scope view+"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Sight holder 1+", pos = Vector(1.76, 0.017, 0), angle = Angle(0, 0, 0), size = Vector(0.013, 0.013, 0.013), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["shroud clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel shroud", pos = Vector(1.267, -3.605, 12.718), angle = Angle(0, 0, 143.47301)},
	["sight base"] = { type = "Model", model = "models/props_vehicles/mining_car.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "RAIL", pos = Vector(1.155, 0.5, 0.004), angle = Angle(90, 0, 0), size = Vector(0.015, 0.017, 0.02), color = Color(54, 54, 54, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/dome", skin = 0, bodygroup = {} },
	["sight base clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sight base", pos = Vector(0.002, -0.082, 0.747), angle = Angle(0, 0, 0)},
	["sight base clip+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sight base+", pos = Vector(0.002, -0.082, 0.747), angle = Angle(0, 0, 0)},
	["sight base+"] = { type = "Model", model = "models/props_vehicles/mining_car.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "RAIL", pos = Vector(1.155, 3.2, 0.004), angle = Angle(-90, 0, 180), size = Vector(0.015, 0.017, 0.02), color = Color(55, 55, 55, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/dome", skin = 0, bodygroup = {} },
	["silencer"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(6.619, -0.053, 0.816), angle = Angle(180, -90, 90), size = Vector(0.17, 0.17, 0.17), color = Color(91, 91, 91, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	--["silencer hole"] = { type = "Model", model = "", bone = "ValveBiped.Bip01_R_Hand", rel = "silencer", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["top frame"] = { type = "Model", model = "models/props_citizen_tech/firetrap_buttonpad.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(-4.3, -0.002, 1.504), angle = Angle(90, 0, 0), size = Vector(0.08, 0.104, 0.31), color = Color(76, 76, 76, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["under back"] = { type = "Model", model = "models/props_c17/display_cooler01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(-2.59, 0, 0.23), angle = Angle(180, -90, 0), size = Vector(0.007, 0.05, 0.027), color = Color(252, 236, 236, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/props_silo/pipesa_bombsite", skin = 0, bodygroup = {} },
	["under front"] = { type = "Model", model = "models/Items/item_item_crate.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(0, 0.024, -0.883), angle = Angle(0, 90, 0), size = Vector(0.022, 0.22, 0.039), color = Color(105, 105, 106, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/metalwall076a", skin = 0, bodygroup = {} }
}

SWEP.ViewModelBoneMods = {}
