AddCSLuaFile()

SWEP.UseHands = true
SWEP.ViewModel = Model("models/weapons/c_irifle.mdl")
SWEP.WorldModel = Model("models/weapons/w_irifle.mdl")

SWEP.ViewModelAttachments = {
	Muzzle = {
		Attachment = "muzzle"
	}
}

SWEP.WorldModelAttachments = {
	Muzzle = {
		Attachment = "muzzle"
	}
}

if SERVER then
	return
end

SWEP.ViewModelFOV = 54
SWEP.ViewModelFlip = false
SWEP.ViewModelOffset = Vector(-3, -0.4, -1)

SWEP.ShowViewModel = false
SWEP.ShowWorldModel = false

SWEP.VElements = {
	["TOP"] = { type = "Model", model = "models/props_interiors/refrigeratorDoor01a.mdl", bone = "Base", rel = "", pos = Vector(-0.01, -2.5, 7.425), angle = Angle(0, 90, 0), size = Vector(0.095, 0.04, 0.209), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["ammobox"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "Base", rel = "", pos = Vector(3.423, 7.816, 14.44), angle = Angle(-90, 90, 0), size = Vector(0.5, 0.5, 0.5), color = Color(91, 91, 76, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_pipes/pipecluster08d_extender64.mdl", bone = "Base", rel = "barrelholder", pos = Vector(0, 0, 13), angle = Angle(0, 0, 0), size = Vector(0.175, 0.175, 0.175), color = Color(114, 114, 114, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["barrelholder"] = { type = "Model", model = "models/hunter/tubes/tube1x1x3.mdl", bone = "Base", rel = "", pos = Vector(0, 0, 14.4), angle = Angle(0, 0, 0), size = Vector(0.045, 0.045, 0.09), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_junk/trafficcone001a", skin = 0, bodygroup = {} },
	["body"] = { type = "Model", model = "models/props_lab/powerbox01a.mdl", bone = "Base", rel = "TOP", pos = Vector(-1.69, 0, -0.68), angle = Angle(0, 0, -180), size = Vector(0.15, 0.05, 0.3), color = Color(66, 68, 48, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/galvanizedmetal", skin = 0, bodygroup = {} },
	["body end"] = { type = "Model", model = "models/props_interiors/refrigerator01a.mdl", bone = "Base", rel = "body", pos = Vector(-0.13, 0, -6.9), angle = Angle(90, 0, 180), size = Vector(0.042, 0.042, 0.042), color = Color(106, 106, 106, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["bolt"] = { type = "Model", model = "models/props_c17/pulleywheels_small01.mdl", bone = "Base", rel = "", pos = Vector(1.31, 0.291, 12), angle = Angle(0, 180, 0), size = Vector(0.06, 0.06, 0.06), color = Color(123, 123, 123, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal1", skin = 0, bodygroup = {} },
	["bolt slot"] = { type = "Model", model = "models/props_wasteland/tram_leverbase01.mdl", bone = "Base", rel = "body", pos = Vector(-1.07, -0.88, -3.576), angle = Angle(90, 0, -90), size = Vector(0.32, 0.11, 0.11), color = Color(93, 93, 93, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bonemerge"] = { type = "Model", model = "models/weapons/c_irifle.mdl", bone = "Base", rel = "", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["brake"] = { type = "Model", model = "models/props_junk/terracotta01.mdl", bone = "Base", rel = "barrel", pos = Vector(0.1, 0, 4.8), angle = Angle(0, -4.528, 0), size = Vector(0.14, 0.14, 0.14), color = Color(255, 226, 38, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/tile/tilefloor001a", skin = 0, bodygroup = {} },
	["clip"] = { type = "ClipPlane", bone = "Base", rel = "bonemerge", pos = Vector(-8.45, 2.684, 0.909), angle = Angle(0, 0, 40.958)},
	["handle"] = { type = "Model", model = "models/props_wasteland/panel_leverHandle001a.mdl", bone = "Base", rel = "body", pos = Vector(1.46, 0.66, -6.45), angle = Angle(0, -129.886, -90), size = Vector(0.265, 0.038, 0.265), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["handle2"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "Base", rel = "handle", pos = Vector(0.1, 2.273, 1.9), angle = Angle(0, 0, -90), size = Vector(0.095, 0.095, 0.152), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_trainstation/trainstation_post001", skin = 0, bodygroup = {} },
	["lower"] = { type = "Model", model = "models/hunter/blocks/cube025x2x025.mdl", bone = "Base", rel = "body", pos = Vector(-1.82, 0.591, -1.55), angle = Angle(0, 0, -90), size = Vector(0.1, 0.1, 0.1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/prodcaution", skin = 0, bodygroup = {} },
	["lower front"] = { type = "Model", model = "models/props_lab/powerbox02c.mdl", bone = "Base", rel = "lower", pos = Vector(-0.88, -4.11, 0.601), angle = Angle(0, 180, -90), size = Vector(0.2, 0.12, 0.2), color = Color(114, 114, 114, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/customs/gunmetal2", skin = 0, bodygroup = {} },
	["lower rear"] = { type = "Model", model = "models/props_lab/monitor01b.mdl", bone = "Base", rel = "lower", pos = Vector(-0.41, 5.3, 0.591), angle = Angle(0, 90, -90), size = Vector(0.14, 0.09, 0.14), color = Color(114, 114, 114, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal2", skin = 0, bodygroup = {} },
	["rail"] = { type = "Model", model = "models/props_interiors/Radiator01a.mdl", bone = "Base", rel = "TOP", pos = Vector(0.07, 0, 0), angle = Angle(0, 0, -90), size = Vector(0.038, 0.152, 0.03), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["side detail"] = { type = "Model", model = "models/props_trainstation/tracksign09.mdl", bone = "Base", rel = "body", pos = Vector(-0.1, 0.61, 2.5), angle = Angle(0, 90, 0), size = Vector(0.132, 0.132, 0.132), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/props_trainstation/TrackSign10.mdl", bone = "Base", rel = "TOP", pos = Vector(0.6, 0, 5), angle = Angle(0, 180, 0), size = Vector(0.038, 0.038, 0.038), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_trainstation/train001", skin = 0, bodygroup = {} },
	["sight back"] = { type = "Model", model = "models/weapons/cstrike/c_mach_m249para.mdl", bone = "Base", rel = "bonemerge", pos = Vector(5.93, -5.91, -10.83), angle = Angle(90, 0, -90), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = true, material = "", skin = 0, bodygroup = {} },
	["sight back clip 1"] = { type = "ClipPlane", bone = "Base", rel = "sight back", pos = Vector(0, 0.04, -3.21), angle = Angle(0, 0, 0)},
	["sight back clip 2"] = { type = "ClipPlane", bone = "Base", rel = "sight back", pos = Vector(15.6, 0.04, -3.21), angle = Angle(90, 0, 0)},
	["stabilizer"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "Base", rel = "", pos = Vector(0, 0.001, 14.52), angle = Angle(90, 90, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer+"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "Base", rel = "stabilizer", pos = Vector(1.6, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer++"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "Base", rel = "stabilizer", pos = Vector(3.233, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer+++"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "Base", rel = "stabilizer", pos = Vector(4.9, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer++++"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "Base", rel = "stabilizer", pos = Vector(6.6, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer+++++"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "Base", rel = "stabilizer", pos = Vector(8.2, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock attach"] = { type = "Model", model = "models/props_c17/furniturebathtub001a.mdl", bone = "Base", rel = "body", pos = Vector(0.06, 0, 7.484), angle = Angle(0, 0, -180), size = Vector(0.055, 0.055, 0.055), color = Color(87, 87, 87, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["stock attach clip"] = { type = "ClipPlane", bone = "Base", rel = "stock attach", pos = Vector(-2.05, 2.41, 0.464), angle = Angle(-6.467, 0, -180)},
	["stock back"] = { type = "Model", model = "models/props/cs_office/phone.mdl", bone = "Base", rel = "stock hold top", pos = Vector(-1.98, 0, 6.69), angle = Angle(0, 180, 180), size = Vector(0.5, 0.2, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock grip"] = { type = "Model", model = "models/props_phx/construct/wood/wood_panel1x2.mdl", bone = "Base", rel = "stock back", pos = Vector(-1.21, 0, -0.077), angle = Angle(0, -90, 0), size = Vector(0.028, 0.05, 0.028), color = Color(123, 123, 123, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "rubber", skin = 0, bodygroup = {} },
	["stock hold top"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "Base", rel = "stock attach", pos = Vector(0.85, 0, -0.75), angle = Angle(0, 0, -180), size = Vector(0.014, 0.014, 0.014), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock hold top+"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "Base", rel = "stock attach", pos = Vector(-1.46, 0, -0.75), angle = Angle(0, 0, -180), size = Vector(0.014, 0.014, 0.014), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock length bttom"] = { type = "Model", model = "models/hunter/tubes/tube1x1x6.mdl", bone = "Base", rel = "stock hold top+", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.01, 0.01, 0.02), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["stock length top"] = { type = "Model", model = "models/hunter/tubes/tube1x1x6.mdl", bone = "Base", rel = "stock hold top", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.01, 0.01, 0.02), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} }
}

SWEP.WElements = {
	["TOP"] = { type = "Model", model = "models/props_interiors/refrigeratorDoor01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "center", pos = Vector(1.31, 0.13, -3.34), angle = Angle(-90, 0, 0), size = Vector(0.095, 0.06, 0.209), color = Color(110, 110, 110, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["ammobox"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "TOP", pos = Vector(-10.252, 2.724, 9.057), angle = Angle(-90, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(91, 91, 76, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_pipes/pipecluster08d_extender64.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelholder", pos = Vector(0, 0, 13), angle = Angle(0, 0, 0), size = Vector(0.175, 0.175, 0.175), color = Color(114, 114, 114, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["barrelholder"] = { type = "Model", model = "models/hunter/tubes/tube1x1x3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "TOP", pos = Vector(-2.5, 0.01, 6.975), angle = Angle(0, -90, 0), size = Vector(0.054, 0.054, 0.095), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_junk/trafficcone001a", skin = 0, bodygroup = {} },
	["bm clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "bonemerge", pos = Vector(0.66, 0, 0), angle = Angle(-94.85, 0, 0)},
	["body"] = { type = "Model", model = "models/props_lab/powerbox01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "TOP", pos = Vector(-1.69, 0, -0.68), angle = Angle(0, 0, -180), size = Vector(0.15, 0.07, 0.3), color = Color(66, 68, 48, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/galvanizedmetal", skin = 0, bodygroup = {} },
	["body end"] = { type = "Model", model = "models/props_interiors/refrigerator01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(-0.13, 0, -6.9), angle = Angle(90, -180, 0), size = Vector(0.042, 0.042, 0.042), color = Color(106, 106, 106, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["bolt"] = { type = "Model", model = "models/props_c17/pulleywheels_small01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(12.871, 2.125, -6.851), angle = Angle(-1.859, -92.192, -101.906), size = Vector(0.06, 0.06, 0.06), color = Color(123, 123, 123, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal1", skin = 0, bodygroup = {} },
	["bolt slot"] = { type = "Model", model = "models/props_wasteland/tram_leverbase01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(-1.08, -1.2, -3.896), angle = Angle(90, -90, 0), size = Vector(0.32, 0.11, 0.11), color = Color(93, 93, 93, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bonemerge"] = { type = "Model", model = "models/weapons/w_irifle.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(0, 0, 0), angle = Angle(2e-05, -1e-05, -1e-05), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["brake"] = { type = "Model", model = "models/props_junk/terracotta01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(0.1, 0, 4.8), angle = Angle(0, -4.528, 0), size = Vector(0.14, 0.14, 0.14), color = Color(255, 226, 38, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/tile/tilefloor001a", skin = 0, bodygroup = {} },
	["center"] = { type = "Model", model = "models/hunter/blocks/cube025x025x025.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(6.71994, 0.21997, -4.95984), angle = Angle(-11.89999, -1.80001, 1.89998), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 0), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["handle"] = { type = "Model", model = "models/props_wasteland/panel_leverHandle001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(1.46, 0.66, -6.45), angle = Angle(0, -129.886, -90), size = Vector(0.265, 0.038, 0.265), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["handle2"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "handle", pos = Vector(0.1, 2.273, 1.9), angle = Angle(0, 0, -90), size = Vector(0.095, 0.095, 0.152), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_trainstation/trainstation_post001", skin = 0, bodygroup = {} },
	["lower"] = { type = "Model", model = "models/hunter/blocks/cube025x2x025.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "lower rear", pos = Vector(5.33, -0.91, -0.66), angle = Angle(-90, -90, 0), size = Vector(0.1, 0.1, 0.147), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/prodcaution", skin = 0, bodygroup = {} },
	["lower front"] = { type = "Model", model = "models/props_lab/powerbox02c.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "lower rear", pos = Vector(10.9, 0, 0.18), angle = Angle(90, 0, 0), size = Vector(0.2, 0.185, 0.2), color = Color(114, 114, 114, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/customs/gunmetal2", skin = 0, bodygroup = {} },
	["lower rear"] = { type = "Model", model = "models/props_lab/monitor01b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "center", pos = Vector(-5.66, 0.121, 0.79), angle = Angle(0, 0, 0), size = Vector(0.14, 0.14, 0.14), color = Color(114, 114, 114, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal2", skin = 0, bodygroup = {} },
	["rail"] = { type = "Model", model = "models/props_interiors/Radiator01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "TOP", pos = Vector(0.07, 0, 0), angle = Angle(0, 0, -90), size = Vector(0.038, 0.152, 0.044), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sb clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sight back", pos = Vector(-9.322, 0.794, 10.625), angle = Angle(0, 0, 0)},
	["sb clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sight back", pos = Vector(-7.062, 0.794, 10.625), angle = Angle(90, 0, 0)},
	["side detail"] = { type = "Model", model = "models/props_trainstation/tracksign09.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(-0.2, 0.31, 2.48), angle = Angle(0, 90, 0), size = Vector(0.132, 0.132, 0.132), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/props_trainstation/TrackSign10.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "TOP", pos = Vector(0.6, 0, 5), angle = Angle(0, 180, 0), size = Vector(0.038, 0.038, 0.038), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_trainstation/train001", skin = 0, bodygroup = {} },
	["sight back"] = { type = "Model", model = "models/weapons/w_mach_m249para.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "TOP", pos = Vector(-10.6, -0.21, 3.87), angle = Angle(90, -180, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = true, material = "", skin = 0, bodygroup = {} },
	["stabilizer"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelholder", pos = Vector(0, 0.001, 0.12), angle = Angle(90, 90, 0), size = Vector(0.068, 0.068, 0.068), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer+"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stabilizer", pos = Vector(3.18, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.068, 0.068, 0.068), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer++"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stabilizer", pos = Vector(6.18, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.068, 0.068, 0.068), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stabilizer+++"] = { type = "Model", model = "models/props_vehicles/tire001b_truck.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stabilizer", pos = Vector(9.18, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.068, 0.068, 0.068), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock attach"] = { type = "Model", model = "models/props_c17/furniturebathtub001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0.06, 0, 7.484), angle = Angle(0, 0, 180), size = Vector(0.055, 0.055, 0.055), color = Color(87, 87, 87, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["stock attach clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "stock attach", pos = Vector(-2.05, 2.41, 0.464), angle = Angle(-6.467, 0, -180)},
	["stock back"] = { type = "Model", model = "models/props/cs_office/phone.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock hold top", pos = Vector(-1.98, 0, 6.69), angle = Angle(0, 180, 180), size = Vector(0.5, 0.2, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock grip"] = { type = "Model", model = "models/props_phx/construct/wood/wood_panel1x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock back", pos = Vector(-1.21, 0, -0.077), angle = Angle(0, -90, 0), size = Vector(0.028, 0.05, 0.028), color = Color(123, 123, 123, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "rubber", skin = 0, bodygroup = {} },
	["stock hold top"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock attach", pos = Vector(0.85, 0, -0.75), angle = Angle(0, 0, -180), size = Vector(0.014, 0.014, 0.014), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock hold top+"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock attach", pos = Vector(-1.46, 0, -0.75), angle = Angle(0, 0, -180), size = Vector(0.014, 0.014, 0.014), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock length bttom"] = { type = "Model", model = "models/hunter/tubes/tube1x1x6.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock hold top+", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.01, 0.01, 0.02), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} },
	["stock length top"] = { type = "Model", model = "models/hunter/tubes/tube1x1x6.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock hold top", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.01, 0.01, 0.02), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/gunmetal6", skin = 0, bodygroup = {} }
}

SWEP.ViewModelBoneMods = {
	["Base"] = { scale = Vector(1, 1, 1), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Claw1"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Claw2"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Reload"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Reload1"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Shell1"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Shell2"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) },
	["Vent"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) }
}
