AddCSLuaFile()

SWEP.UseHands = true
SWEP.ViewModel = Model("models/weapons/c_shotgun.mdl")
SWEP.WorldModel = Model("models/weapons/w_shotgun.mdl")

if SERVER then
	return
end

SWEP.ViewModelFOV = 54
SWEP.ViewModelFlip = false

SWEP.ShowViewModel = false
SWEP.ShowWorldModel = false

SWEP.VElements = {
	["Body"] = { type = "Model", model = "models/props_combine/CombineTrain01a.mdl", bone = "ValveBiped.Gun", rel = "", pos = Vector(0.046, 2.982, 1.646), angle = Angle(-90, 90, 0), size = Vector(0.046, 0.02, 0.017), color = Color(33, 33, 33, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = true, material = "metal2", skin = 0, bodygroup = {} },
	["Body clip +"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "Body", pos = Vector(4.606, -1.803, -1.299), angle = Angle(-90, 0, 0)},
	["emitter"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter back", pos = Vector(0, 0, 4.4), angle = Angle(90, 0, 0), size = Vector(0.14, 0.14, 0.14), color = Color(16, 16, 16, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["Laser"] = { type = "Laser", rel = "emitter", pos = Vector(0, 0, 0), angle = Angle(), length = 40, width = 3, brightness = 10, color = Color(255, 0, 0)},
	["emitter back"] = { type = "Model", model = "models/xqm/pistontype1large.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter base", pos = Vector(0, 0, -0.6), angle = Angle(0, -90, 0), size = Vector(0.065, 0.065, 0.065), color = Color(16, 16, 16, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter back clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "emitter back", pos = Vector(0.629, 2.171, 1.635), angle = Angle(0, 0, 0)},
	["emitter base"] = { type = "Model", model = "models/props_silo/rocket_stage3.mdl", bone = "ValveBiped.Gun", rel = "", pos = Vector(0.114, 3.2, 11.143), angle = Angle(-0.002, 0.001, 0.229), size = Vector(0.009, 0.009, 0.01), color = Color(53, 53, 53, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter connect"] = { type = "Model", model = "models/props_phx/misc/iron_beam1.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter base", pos = Vector(0.001, -1.274, 1.688), angle = Angle(90, 0, 90), size = Vector(0.065, 0.073, 0.073), color = Color(78, 78, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
	["emitter light"] = { type = "Model", model = "models/Combine_Helicopter/helicopter_bomb01.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter", pos = Vector(0.68, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.04, 0.04, 0), color = Color(206, 206, 206, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["frontcover"] = { type = "Model", model = "models/hunter/misc/roundthing2.mdl", bone = "ValveBiped.Gun", rel = "Body", pos = Vector(-8.7, 0, 2.566), angle = Angle(0, 90, 90), size = Vector(0.043, 0.031, 0.01), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["heat vent"] = { type = "Model", model = "models/hunter/plates/plate05x5.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Body", pos = Vector(-1.87, 0, 4.599), angle = Angle(0, 90, 0), size = Vector(0.06, 0.057, 0.05), color = Color(91, 86, 86, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/metal/nuke_floor_trim_01", skin = 0, bodygroup = {} },
	["lens back"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(2.2, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.102, 0.102, 0.102), color = Color(255, 0, 0, 254), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["lens back+"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(-1.747, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.111, 0.111, 0.111), color = Color(255, 0, 0, 254), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["lower"] = { type = "Model", model = "models/props_combine/combine_train02a.mdl", bone = "ValveBiped.Gun", rel = "Body", pos = Vector(-1.346, 0.06, 2.622), angle = Angle(9.057, 90, 0), size = Vector(0.025, 0.026, 0.019), color = Color(199, 180, 180, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "", skin = 0, bodygroup = {} },
	["lower clip"] = { type = "ClipPlane", bone = "ValveBiped.Gun", rel = "lower", pos = Vector(0, -0.51, -9.59), angle = Angle(90, 0, 0)},
	["lower clip+"] = { type = "ClipPlane", bone = "ValveBiped.Gun", rel = "lower+", pos = Vector(0, -0.51, -9.59), angle = Angle(-90, 0, 0)},
	["lower+"] = { type = "Model", model = "models/props_combine/combine_train02a.mdl", bone = "ValveBiped.Gun", rel = "Body", pos = Vector(-1.346, -0.05, 2.622), angle = Angle(-9.057, 90, 0), size = Vector(0.025, 0.026, 0.019), color = Color(199, 180, 180, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["muzzle"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Body", pos = Vector(-20.07, 0, 3.5), angle = Angle(-90, 0, 0), size = Vector(0.037, 0.037, 0.037), color = Color(95, 95, 95, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["pump"] = { type = "Model", model = "models/combine_gate_vehicle.mdl", bone = "ValveBiped.Pump", rel = "", pos = Vector(0.54, 1.98, 4.736), angle = Angle(0, -13, -90), size = Vector(0.019, 0.054, 0.015), color = Color(23, 23, 23, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/combine_scanner/scanner_eye", skin = 0, bodygroup = {} },
	["pump connector"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter connect", pos = Vector(0, -0.066, -0.41), angle = Angle(90, 0, 0), size = Vector(0.016, 0.016, 0.016), color = Color(99, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["pump connector+"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter connect", pos = Vector(1.51, -0.066, -0.41), angle = Angle(90, 0, 0), size = Vector(0.016, 0.016, 0.016), color = Color(99, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["pump+"] = { type = "Model", model = "models/combine_gate_vehicle.mdl", bone = "ValveBiped.Pump", rel = "", pos = Vector(-0.43, 1.98, 4.75), angle = Angle(0, 13, 90), size = Vector(-0.019, -0.054, -0.015), color = Color(23, 23, 23, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/combine_scanner/scanner_eye", skin = 0, bodygroup = {} },
	["rail"] = { type = "Model", model = "models/props_junk/TrashDumpster01a.mdl", bone = "ValveBiped.Gun", rel = "Body", pos = Vector(8, 0.06, 4.48), angle = Angle(0, -90, 0), size = Vector(0.023, 0.07, 0.022), color = Color(65, 65, 65, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["rail+"] = { type = "Model", model = "models/props_junk/TrashDumpster01a.mdl", bone = "ValveBiped.Gun", rel = "Body", pos = Vector(7.994, 0.8, 3.768), angle = Angle(-90, -90, 0), size = Vector(0.023, 0.07, 0.022), color = Color(65, 65, 65, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Gun", rel = "sightbase", pos = Vector(1.24, 0, 0), angle = Angle(90, 90, 0), size = Vector(0.04, 0.025, 0.025), color = Color(44, 44, 44, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/dome", skin = 0, bodygroup = {} },
	["sight adjust 1"] = { type = "Model", model = "models/xqm/cylinderx1.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(0, 0.62, 0), angle = Angle(0, 90, 0), size = Vector(0.08, 0.08, 0.08), color = Color(44, 44, 44, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight adjust 1+"] = { type = "Model", model = "models/xqm/cylinderx1.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(0, 0, -0.64), angle = Angle(90, -180, 0), size = Vector(0.08, 0.08, 0.08), color = Color(63, 63, 63, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight adjust clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "sight adjust 1", pos = Vector(-0.305, -0.254, -0.007), angle = Angle(90, 0, 0)},
	["sight adjust clip+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "sight adjust 1+", pos = Vector(-0.305, -0.254, -0.007), angle = Angle(90, 0, 0)},
	["sight adjust wheel"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight adjust 1", pos = Vector(-0.587, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.008, 0.008, 0.008), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["sight adjust wheel+"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight adjust 1+", pos = Vector(-0.587, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.008, 0.008, 0.008), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["sight inner"] = { type = "Model", model = "models/props_phx/wheels/magnetic_medium.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(-2, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.061, 0.061, 0.54), color = Color(167, 167, 167, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight sprite"] = { type = "Sprite", sprite = "sprites/ledglow", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(0.961, 0, 0), size = { x = 1, y = 1 }, color = Color(255, 255, 255, 255), nocull = true, additive = true, vertexalpha = true, vertexcolor = true, ignorez = false},
	["sightbase"] = { type = "Model", model = "models/props_lab/powerbox02b.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "rail", pos = Vector(-0.033, 0, 0.54), angle = Angle(90, -90, 0), size = Vector(0.06, 0.08, 0.11), color = Color(23, 23, 23, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/trains/track_plateside", skin = 0, bodygroup = {} },
	["sighthood"] = { type = "Model", model = "models/props_mining/antlion_detector_lights_lamp.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sight", pos = Vector(1.589, -2.534, -2.615), angle = Angle(180, 0, 90), size = Vector(0.19, 0.255, 0.255), color = Color(167, 167, 167, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
	["sighthood clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "sighthood", pos = Vector(3.416, -0.297, -0.299), angle = Angle(-90, 0, 0)},
	["silencer"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "muzzle", pos = Vector(0, 0, -4.78), angle = Angle(0, 0, 0), size = Vector(0.3, 0.3, 0.3), color = Color(74, 74, 74, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["silencerhole"] = { type = "Model", model = "models/props_phx/misc/potato_launcher_chamber.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "silencer", pos = Vector(0, -0.06, -5.3), angle = Angle(0, 0, 180), size = Vector(0.16, 0.16, 0.01), color = Color(102, 102, 102, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["silencerhole_c"] = { type = "Model", model = "models/props_phx/misc/potato_launcher_chamber.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "emitter", pos = Vector(0.7, 0, 0), angle = Angle(-89.999, -0.002, 0), size = Vector(0.1, 0.1, 0.009), color = Color(125, 125, 125, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "rubber", skin = 0, bodygroup = {} },
	["silencerholehole"] = { type = "Model", model = "models/props_trainstation/trainstation_clock001.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "silencerhole", pos = Vector(0, 0, -0.54), angle = Angle(90, 0, 0), size = Vector(0, 0.02, 0.02), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["true body"] = { type = "Model", model = "models/weapons/c_shotgun.mdl", bone = "ValveBiped.Gun", rel = "", pos = Vector(0, 27.17, 10.063), angle = Angle(1.132, -93.962, 180), size = Vector(0.5, 0.5, 0.5), color = Color(221, 232, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["under"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "ValveBiped.Gun", rel = "Body", pos = Vector(-0.138, 0, 2.99), angle = Angle(0, 90, 180), size = Vector(0.17, 0.9, 0.2), color = Color(159, 127, 131, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.WElements = {
	["Body"] = { type = "Model", model = "models/props_combine/CombineTrain01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(20.872, 0.693, -2.851), angle = Angle(5.503, -178.709, -174.298), size = Vector(0.046, 0.02, 0.017), color = Color(33, 33, 33, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = true, material = "metal2", skin = 0, bodygroup = {} },
	["Body clip +"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(4.60617, -1.80292, -1.299), angle = Angle(-89.99993, 3e-05, 0)},
	["base"] = { type = "Model", model = "models/weapons/w_shotgun.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter back", pos = Vector(0, 0, 4.4), angle = Angle(90, 0, 0), size = Vector(0.14, 0.14, 0.14), color = Color(16, 16, 16, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["Laser"] = { type = "Laser", rel = "emitter", pos = Vector(0, 0, 0), angle = Angle(), length = 40, width = 3, brightness = 10, color = Color(255, 0, 0)},
	["emitter back"] = { type = "Model", model = "models/xqm/pistontype1large.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter base", pos = Vector(0, 0, -1.288), angle = Angle(0, -90, 0), size = Vector(0.065, 0.065, 0.065), color = Color(16, 16, 16, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter back clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter back", pos = Vector(0.629, 2.171, 1.635), angle = Angle(0, 0, 0)},
	["emitter base"] = { type = "Model", model = "models/props_silo/rocket_stage3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "pump connector", pos = Vector(1.804, 0.065, 1.3), angle = Angle(0, -90, -180), size = Vector(0.009, 0.009, 0.009), color = Color(53, 53, 53, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["emitter connect"] = { type = "Model", model = "models/props_phx/misc/iron_beam1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "pump connector", pos = Vector(0.40999, 0.06592, 0.00015), angle = Angle(-89.99998, 0, 0), size = Vector(0.065, 0.073, 0.073), color = Color(78, 78, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
	["emitter light"] = { type = "Model", model = "models/Combine_Helicopter/helicopter_bomb01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter", pos = Vector(0.68, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.04, 0.04, 0), color = Color(206, 206, 206, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["frontcover"] = { type = "Model", model = "models/hunter/misc/roundthing2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(-5.88989, -0.01978, 2.596), angle = Angle(1e-05, 89.99999, 90), size = Vector(0.043, 0.031, 0.01), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["heat vent"] = { type = "Model", model = "models/hunter/plates/plate05x5.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(-0.28992, 0.00018, 4.599), angle = Angle(0, 90, 0), size = Vector(0.06, 0.043, 0.05), color = Color(91, 86, 86, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "de_nuke/nuke_floor_trim_01", skin = 0, bodygroup = {} },
	["lens back"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(2.2, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.102, 0.102, 0.102), color = Color(255, 0, 0, 252), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["lens back+"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(-1.747, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.111, 0.111, 0.111), color = Color(255, 0, 0, 252), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["lower"] = { type = "Model", model = "models/props_combine/combine_train02a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(0.19418, 0.06006, 2.62198), angle = Angle(9.057, 89.99998, 0), size = Vector(0.025, 0.02, 0.019), color = Color(199, 180, 180, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["lower clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "lower", pos = Vector(-1e-05, -0.51007, -9.59001), angle = Angle(90, 0, 0)},
	["lower clip+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "lower+", pos = Vector(0, -0.51, -9.59), angle = Angle(-90, 0, 0)},
	["lower+"] = { type = "Model", model = "models/props_combine/combine_train02a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "lower", pos = Vector(0.109, 0, -0.017), angle = Angle(-18.114, 0, 0), size = Vector(0.025, 0.02, 0.019), color = Color(199, 180, 180, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["muzzle"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(-9.64, 0, 3.72), angle = Angle(-90, 0, 0), size = Vector(0.037, 0.037, 0.037), color = Color(95, 95, 95, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["pump"] = { type = "Model", model = "models/combine_gate_vehicle.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(-0.46994, 0.4942, 1.002), angle = Angle(-13, -89.99998, 0), size = Vector(0.019, 0.04, 0.015), color = Color(23, 23, 23, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/combine_scanner/scanner_eye", skin = 0, bodygroup = {} },
	["pump connector"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(-7.352, 0.033, 2.339), angle = Angle(-89.771, -0.248, -0.25), size = Vector(0.016, 0.016, 0.016), color = Color(99, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["pump connector+"] = { type = "Model", model = "models/props_phx/construct/metal_plate_curve360x2.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "pump connector", pos = Vector(-2e-05, 0, -1.50998), angle = Angle(0, 0, -2e-05), size = Vector(0.016, 0.016, 0.016), color = Color(99, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["pump+"] = { type = "Model", model = "models/combine_gate_vehicle.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "pump", pos = Vector(-0.94516, 0.01398, -0.2182), angle = Angle(26.00001, 1e-05, -180), size = Vector(-0.019, -0.04, -0.015), color = Color(23, 23, 23, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/combine_scanner/scanner_eye", skin = 0, bodygroup = {} },
	["rail"] = { type = "Model", model = "models/props_junk/TrashDumpster01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(8.00009, 0.06, 4.48), angle = Angle(0, -89.99998, 0), size = Vector(0.023, 0.07, 0.022), color = Color(65, 65, 65, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["rail+"] = { type = "Model", model = "models/props_junk/TrashDumpster01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(7.99408, 0.80011, 3.76801), angle = Angle(-90, -89.99996, 0), size = Vector(0.023, 0.07, 0.022), color = Color(65, 65, 65, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sightbase", pos = Vector(1.24, 0, 0), angle = Angle(90, 90, 0), size = Vector(0.04, 0.025, 0.025), color = Color(44, 44, 44, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/dome", skin = 0, bodygroup = {} },
	["sight adjust 1"] = { type = "Model", model = "models/xqm/cylinderx1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(0, 0.62, 0), angle = Angle(0, 90, 0), size = Vector(0.08, 0.08, 0.08), color = Color(44, 44, 44, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight adjust 1+"] = { type = "Model", model = "models/xqm/cylinderx1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(0, 0, -0.64), angle = Angle(90, -180, 0), size = Vector(0.08, 0.08, 0.08), color = Color(63, 63, 63, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight adjust clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sight adjust 1", pos = Vector(-0.305, -0.254, -0.007), angle = Angle(90, 0, 0)},
	["sight adjust clip+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sight adjust 1+", pos = Vector(-0.305, -0.254, -0.007), angle = Angle(90, 0, 0)},
	["sight adjust wheel"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight adjust 1", pos = Vector(-0.587, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.008, 0.008, 0.008), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["sight adjust wheel+"] = { type = "Model", model = "models/Mechanics/gears2/gear_60t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight adjust 1+", pos = Vector(-0.587, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.008, 0.008, 0.008), color = Color(89, 89, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["sight inner"] = { type = "Model", model = "models/props_phx/wheels/magnetic_medium.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(-2, 0, 0), angle = Angle(-90, 0, 0), size = Vector(0.061, 0.061, 0.54), color = Color(167, 167, 167, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sight sprite"] = { type = "Sprite", sprite = "sprites/ledglow", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(0.961, 0, 0), size = { x = 1, y = 1 }, color = Color(255, 255, 255, 255), nocull = true, additive = true, vertexalpha = true, vertexcolor = true, ignorez = false},
	["sightbase"] = { type = "Model", model = "models/props_lab/powerbox02b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "rail", pos = Vector(-0.033, 0, 0.54), angle = Angle(90, -90, 0), size = Vector(0.06, 0.08, 0.11), color = Color(23, 23, 23, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/trains/track_plateside", skin = 0, bodygroup = {} },
	["sighthood"] = { type = "Model", model = "models/props_mining/antlion_detector_lights_lamp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sight", pos = Vector(1.589, -2.534, -2.615), angle = Angle(180, 0, 90), size = Vector(0.19, 0.255, 0.255), color = Color(167, 167, 167, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
	["sighthood clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sighthood", pos = Vector(3.416, -0.297, -0.299), angle = Angle(-90, 0, 0)},
	["silencer"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "muzzle", pos = Vector(0, 0, -4.78), angle = Angle(0, 0, 0), size = Vector(0.3, 0.3, 0.3), color = Color(74, 74, 74, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
	["silencerhole"] = { type = "Model", model = "models/props_phx/misc/potato_launcher_chamber.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "silencer", pos = Vector(0, -0.06, -5.3), angle = Angle(0, 0, 180), size = Vector(0.16, 0.16, 0.01), color = Color(102, 102, 102, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal6", skin = 0, bodygroup = {} },
	["silencerhole_c"] = { type = "Model", model = "models/props_phx/misc/potato_launcher_chamber.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "emitter", pos = Vector(0.7, 0, 0), angle = Angle(-89.999, -0.002, 0), size = Vector(0.1, 0.1, 0.009), color = Color(125, 125, 125, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "rubber", skin = 0, bodygroup = {} },
	["silencerholehole"] = { type = "Model", model = "models/props_trainstation/trainstation_clock001.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "silencerhole", pos = Vector(0, 0, -0.54), angle = Angle(90, 0, 0), size = Vector(0.001, 0.02, 0.02), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["under"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Body", pos = Vector(-0.13791, 0, 2.99), angle = Angle(0, 89.99999, -179.99998), size = Vector(0.17, 0.61, 0.2), color = Color(159, 127, 131, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.ViewModelBoneMods = {
	["ValveBiped.Pump"] = { scale = Vector(0.01, 0.01, 0.01), pos = Vector(0, 0, 0), angle = Angle(0, 0, 0) }
}



