AddCSLuaFile()

SWEP.UseHands = true
SWEP.ViewModel = Model("models/weapons/c_smg1.mdl")
SWEP.WorldModel = Model("models/weapons/w_smg1.mdl")

if SERVER then
	return
end

SWEP.ViewModelFOV = 55
SWEP.ViewModelFlip = false

SWEP.ShowViewModel = true
SWEP.ShowWorldModel = true

SWEP.IronSightsPos = Vector(0, 0, 0)
SWEP.IronSightsAng = Vector(0, 0, 0)

SWEP.VElements = {
	["barrel"] = { type = "Model", model = "models/props_rooftop/chimneypipe01a.mdl", bone = "ValveBiped.base", rel = "frontbarrelholder", pos = Vector(0, 1, 0), angle = Angle(-90, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrelmain+"] = { type = "Model", model = "models/xqm/jetbody2fuselage.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "body", pos = Vector(0, 12.01, 1.964), angle = Angle(0, -90, -180), size = Vector(0.23, 0.045, 0.1), color = Color(209, 220, 250, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/polymer3", skin = 0, bodygroup = {} },
	["body"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "ValveBiped.base", rel = "", pos = Vector(0, 1.5, 0), angle = Angle(0, 0, -90), size = Vector(0.16, 0.492, 0.265), color = Color(106, 106, 106, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bolt"] = { type = "Model", model = "models/props_c17/TrapPropeller_Lever.mdl", bone = "ValveBiped.base", rel = "mech", pos = Vector(1.364, -1.364, 2.6), angle = Angle(0, -90, 0), size = Vector(0.152, 0.095, 0.379), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["clip"] = { type = "Model", model = "models/Items/BoxSRounds.mdl", bone = "ValveBiped.base", rel = "mech", pos = Vector(-4.6, 0, 2), angle = Angle(-90, 0, 0), size = Vector(0.265, 0.265, 0.322), color = Color(106, 104, 106, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["cover"] = { type = "Model", model = "models/props_interiors/VendingMachineSoda01a_door.mdl", bone = "ValveBiped.base", rel = "barrelmain+", pos = Vector(-1.91, 0, -1.46), angle = Angle(90, 0, 0), size = Vector(0.09, 0.015, 0.12), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["flashlight"] = { type = "Model", model = "models/props_wasteland/light_spotlight01_lamp.mdl", bone = "ValveBiped.base", rel = "frontbarrelholder", pos = Vector(1.364, 0.3, 0), angle = Angle(0, 0, -90), size = Vector(0.209, 0.06, 0.06), color = Color(92, 96, 96, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["foregrip"] = { type = "Model", model = "models/weapons/cstrike/c_smg_ump45.mdl", bone = "ValveBiped.base", rel = "foregrip holder", pos = Vector(-9.15, 10.07, 40.72), angle = Angle(-90, 0, 180), size = Vector(1.2, 1.2, 1.2), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["foregrip clip 1"] = { type = "ClipPlane", bone = "ValveBiped.base", rel = "foregrip", pos = Vector(41.92, 2.86, -9.68), angle = Angle(153.054, 0, 0)},
	["foregrip clip2"] = { type = "ClipPlane", bone = "ValveBiped.base", rel = "foregrip", pos = Vector(39.67, 2.85, -9.65), angle = Angle(-92.695, 0, 0)},
	["foregrip holder"] = { type = "Model", model = "models/props_mining/indicator_updown01.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "barrelmain+", pos = Vector(-2.62, 0.02, 1.17), angle = Angle(90, 0, 0), size = Vector(0.35, 0.244, 0.35), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["frontbarrelholder"] = { type = "Model", model = "models/props_c17/pulleywheels_small01.mdl", bone = "ValveBiped.base", rel = "barrelmain+", pos = Vector(3.46, 0, 0.11), angle = Angle(0, 0, 90), size = Vector(0.265, 0.18, 0.09), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["grip"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.base", rel = "", pos = Vector(0, 6.12, -1.96), angle = Angle(90, -90, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["mech"] = { type = "Model", model = "models/props_lab/citizenradio.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.13, 0.237, 0.2), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["railtoprail"] = { type = "Model", model = "models/props_c17/FurnitureRadiator001a.mdl", bone = "ValveBiped.base", rel = "toprial", pos = Vector(-0.08, 0, 0), angle = Angle(0, 0, -90), size = Vector(0.04, 0.12, 0.024), color = Color(128, 125, 128, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["siderail l"] = { type = "Model", model = "models/Mechanics/gears2/pinion_40t3.mdl", bone = "ValveBiped.base", rel = "barrelmain+", pos = Vector(-1.44, 0.95, 0), angle = Angle(0, 0.65, 0), size = Vector(0.079, 0.04, 0.06), color = Color(101, 104, 98, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/grixis/customs/gunmetal1", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/props_c17/utilitypolemount01a.mdl", bone = "ValveBiped.base", rel = "barrelmain+", pos = Vector(4.471, 0, -2.2), angle = Angle(0, -90, -90), size = Vector(0.095, 0.03, 0.03), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock"] = { type = "Model", model = "models/props_junk/iBeam01a.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(-0.03, -3.16, 3.12), angle = Angle(0, -90, 90), size = Vector(0.06, 0.06, 0.06), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock lower"] = { type = "Model", model = "models/props_junk/iBeam01a.mdl", bone = "ValveBiped.base", rel = "stock", pos = Vector(0, 1.42, 0), angle = Angle(0, 0, 0), size = Vector(0.06, 0.06, 0.06), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock slope"] = { type = "Model", model = "models/props_lab/scrapyarddumpster_static.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "stock", pos = Vector(-6.038, -0.4, 0.02), angle = Angle(0, 0, 90), size = Vector(0.04, 0.008, 0.043), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock slope cover"] = { type = "Model", model = "models/props_junk/TrashDumpster02b.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "stock slope", pos = Vector(0.48, 0, 3.38), angle = Angle(0, 90, 40), size = Vector(0.01, 0.023, 0.014), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stockback"] = { type = "Model", model = "models/props_combine/combine_barricade_tall01a.mdl", bone = "ValveBiped.base", rel = "stockpress", pos = Vector(1.2, 0, -2.3), angle = Angle(-90.566, 0, -180), size = Vector(0.016, 0.016, 0.025), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stockpress"] = { type = "Model", model = "models/props_c17/FurnitureWashingmachine001a.mdl", bone = "ValveBiped.base", rel = "stock slope", pos = Vector(-3.94, 0.02, 2.24), angle = Angle(90, -180, 0), size = Vector(0.165, 0.038, 0.12), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["top"] = { type = "Model", model = "models/Items/car_battery01.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(0, 0, 3), angle = Angle(0, 180, 180), size = Vector(0.152, 0.669, 0.152), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprail"] = { type = "Model", model = "models/props_interiors/Radiator01a.mdl", bone = "ValveBiped.base", rel = "cover", pos = Vector(-0.27, 0, 0.138), angle = Angle(0, 0, 90), size = Vector(0.05, 0.209, 0.02), color = Color(47, 50, 49, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprailback"] = { type = "Model", model = "models/props_trainstation/mount_connection001a.mdl", bone = "ValveBiped.base", rel = "top", pos = Vector(0, -3.84, -1.3), angle = Angle(0, 90, 0), size = Vector(0.038, 0.05, 0.038), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprailback+"] = { type = "Model", model = "models/props_trainstation/mount_connection001a.mdl", bone = "ValveBiped.base", rel = "top", pos = Vector(0, 3.84, -1.3), angle = Angle(0, -90, 0), size = Vector(0.038, 0.05, 0.038), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprial"] = { type = "Model", model = "models/props_lab/filecabinet02.mdl", bone = "ValveBiped.base", rel = "toprailback", pos = Vector(-3.9, 0, -0.67), angle = Angle(90, 0, -180), size = Vector(0.01, 0.05, 0.187), color = Color(64, 63, 66, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["topsupp"] = { type = "Model", model = "models/props_lab/reciever01b.mdl", bone = "ValveBiped.base", rel = "top", pos = Vector(0, -0.7, -1.364), angle = Angle(0, 90, 180), size = Vector(0.152, 0.069, 0.152), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.WElements = {
	["barrel"] = { type = "Model", model = "models/props_rooftop/chimneypipe01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "frontbarrelholder", pos = Vector(0, 1, 0), angle = Angle(-90, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrelmain"] = { type = "Model", model = "models/xqm/jetbody2fuselage.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0, 12.01, 1.964), angle = Angle(0, -90, 180), size = Vector(0.23, 0.045, 0.1), color = Color(209, 220, 250, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/polymer3", skin = 0, bodygroup = {} },
	["body"] = { type = "Model", model = "models/Items/BoxMRounds.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(5.411, 1.518, -2.758), angle = Angle(2.854, -88.986, 169.795), size = Vector(0.16, 0.492, 0.265), color = Color(106, 106, 106, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bolt"] = { type = "Model", model = "models/props_c17/TrapPropeller_Lever.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "mech", pos = Vector(1.364, -1.364, 2.6), angle = Angle(0, -90, 0), size = Vector(0.152, 0.095, 0.379), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["clip"] = { type = "Model", model = "models/Items/BoxSRounds.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "mech", pos = Vector(-4.6, 0, 2), angle = Angle(-90, 0, 0), size = Vector(0.265, 0.265, 0.322), color = Color(106, 104, 106, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["cover"] = { type = "Model", model = "models/props_interiors/VendingMachineSoda01a_door.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelmain", pos = Vector(-1.91, 0, -1.46), angle = Angle(90, 0, 0), size = Vector(0.09, 0.015, 0.12), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["fg clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "foregrip", pos = Vector(0.94, -1.35, 7.436), angle = Angle(0, 0, 180)},
	["fg clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "foregrip", pos = Vector(8.7, -1.55, 4.556), angle = Angle(90, 0, 180)},
	["flashlight"] = { type = "Model", model = "models/props_wasteland/light_spotlight01_lamp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "frontbarrelholder", pos = Vector(1.364, 0.3, 0), angle = Angle(0, 0, -90), size = Vector(0.209, 0.06, 0.06), color = Color(92, 96, 96, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["foregrip"] = { type = "Model", model = "models/weapons/w_smg_ump45.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "foregrip holder", pos = Vector(8.2, -0.15, 10.13), angle = Angle(-90, 0, 180), size = Vector(1.2, 1.2, 1.2), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["foregrip holder"] = { type = "Model", model = "models/props_mining/indicator_updown01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelmain", pos = Vector(-2.62, 0.02, 1.17), angle = Angle(90, 0, 0), size = Vector(0.35, 0.244, 0.35), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["frontbarrelholder"] = { type = "Model", model = "models/props_c17/pulleywheels_small01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelmain", pos = Vector(3.46, 0, 0.11), angle = Angle(0, 0, 90), size = Vector(0.265, 0.18, 0.09), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["grip"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0, -1.96, -5.2), angle = Angle(0, -90, 0), size = Vector(1, 1, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["mech"] = { type = "Model", model = "models/props_lab/citizenradio.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.13, 0.237, 0.2), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["railtoprail"] = { type = "Model", model = "models/props_c17/FurnitureRadiator001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "toprial", pos = Vector(-0.08, 0, 0), angle = Angle(0, 0, -90), size = Vector(0.04, 0.12, 0.024), color = Color(128, 125, 128, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["siderail l"] = { type = "Model", model = "models/Mechanics/gears2/pinion_40t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelmain", pos = Vector(-1.44, 0.95, 0), angle = Angle(0, 0.65, 0), size = Vector(0.079, 0.04, 0.06), color = Color(101, 104, 98, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/grixis/customs/gunmetal1", skin = 0, bodygroup = {} },
	["siderail r"] = { type = "Model", model = "models/Mechanics/gears2/pinion_40t3.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelmain", pos = Vector(-1.44, -1, 0), angle = Angle(0, 179.395, 0), size = Vector(0.079, 0.04, 0.06), color = Color(101, 104, 98, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/grixis/customs/gunmetal1", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/props_c17/utilitypolemount01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrelmain", pos = Vector(4.471, 0, -2.2), angle = Angle(0, -90, -90), size = Vector(0.095, 0.03, 0.03), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock"] = { type = "Model", model = "models/props_junk/iBeam01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(-0.03, -3.16, 3.12), angle = Angle(0, -90, 90), size = Vector(0.06, 0.06, 0.06), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock lower"] = { type = "Model", model = "models/props_junk/iBeam01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock", pos = Vector(0, 1.42, 0), angle = Angle(0, 0, 0), size = Vector(0.06, 0.06, 0.06), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock slope"] = { type = "Model", model = "models/props_lab/scrapyarddumpster_static.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock", pos = Vector(-6.038, -0.4, 0.02), angle = Angle(0, 0, 90), size = Vector(0.04, 0.008, 0.043), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock slope cover"] = { type = "Model", model = "models/props_junk/TrashDumpster02b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock slope", pos = Vector(0.48, 0, 3.38), angle = Angle(0, 90, 40), size = Vector(0.01, 0.023, 0.014), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stockback"] = { type = "Model", model = "models/props_combine/combine_barricade_tall01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stockpress", pos = Vector(1.2, 0, -2.3), angle = Angle(-90.566, 0, -180), size = Vector(0.016, 0.016, 0.025), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stockpress"] = { type = "Model", model = "models/props_c17/FurnitureWashingmachine001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock slope", pos = Vector(-3.94, 0.02, 2.24), angle = Angle(90, -180, 0), size = Vector(0.165, 0.038, 0.12), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["top"] = { type = "Model", model = "models/Items/car_battery01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0, 0, 3), angle = Angle(0, 180, 180), size = Vector(0.152, 0.669, 0.152), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprail"] = { type = "Model", model = "models/props_interiors/Radiator01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "cover", pos = Vector(-0.27, 0, 0.138), angle = Angle(0, 0, 90), size = Vector(0.05, 0.209, 0.02), color = Color(47, 50, 49, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprailback"] = { type = "Model", model = "models/props_trainstation/mount_connection001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "top", pos = Vector(0, -3.84, -1.3), angle = Angle(0, 90, 0), size = Vector(0.038, 0.05, 0.038), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprailback+"] = { type = "Model", model = "models/props_trainstation/mount_connection001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "top", pos = Vector(0, 3.84, -1.3), angle = Angle(0, -90, 0), size = Vector(0.038, 0.05, 0.038), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["toprial"] = { type = "Model", model = "models/props_lab/filecabinet02.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "toprailback", pos = Vector(-3.9, 0, -0.67), angle = Angle(90, 0, -180), size = Vector(0.01, 0.05, 0.187), color = Color(64, 63, 66, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["topsupp"] = { type = "Model", model = "models/props_lab/reciever01b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "top", pos = Vector(0, -0.7, -1.364), angle = Angle(0, 90, 180), size = Vector(0.152, 0.069, 0.152), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}


	["ValveBiped.Bip01_L_Clavicle"] = { scale = Vector(1, 1, 1), pos = Vector(2.156, -1.796, -0.3), angle = Angle(0, 0, 0) },
	["ValveBiped.Bip01_L_Forearm"] = { scale = Vector(1, 1, 1), pos = Vector(0, 0, 0), angle = Angle(0, 19.401, 0) },
	["ValveBiped.Bip01_L_Hand"] = { scale = Vector(1, 1, 1), pos = Vector(0, 0, 0), angle = Angle(-6, -8.623, 0) },
	["ValveBiped.Bip01_R_Clavicle"] = { scale = Vector(1, 1, 1), pos = Vector(1.078, -0.359, 0), angle = Angle(0, 0, 0) },
	["ValveBiped.Bip01_R_Hand"] = { scale = Vector(1, 1, 1), pos = Vector(0, 0, 0), angle = Angle(-12.934, 0, 0) },
	["ValveBiped.Bip01_Spine4"] = { scale = Vector(1, 1, 1), pos = Vector(-2.874, 0, -0.359), angle = Angle(0, 0, 0) },
	["ValveBiped.base"] = { scale = Vector(1, 1, 1), pos = Vector(0, 0, -2.874), angle = Angle(0, 0, 0) }
}



