AddCSLuaFile()

SWEP.UseHands = true
SWEP.ViewModel = Model("models/weapons/c_smg1.mdl")
SWEP.WorldModel = Model("models/weapons/w_smg1.mdl")

if SERVER then
	return
end

SWEP.ViewModelFOV = 55
SWEP.ViewModelFlip = false

SWEP.ShowViewModel = false
SWEP.ShowWorldModel = false

SWEP.VElements = {
	["back"] = { type = "Model", model = "models/props_lab/kennel_physics.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(-1.861, -11.26, 0), angle = Angle(0, -90, -90), size = Vector(0.043, 0.05, 0.08), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_rooftop/roof_vent002.mdl", bone = "ValveBiped.base", rel = "front", pos = Vector(0, -0.3, 4.987), angle = Angle(0, 0, 0), size = Vector(0.18, 0.18, 0.18), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "barrel", pos = Vector(0, -0.11, 0.33), angle = Angle(0, 0, 0)},
	["body"] = { type = "Model", model = "models/props_lab/reciever01a.mdl", bone = "ValveBiped.base", rel = "", pos = Vector(0, -0.6, 2.76), angle = Angle(0, 90, -90), size = Vector(0.237, 0.4, 0.172), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["body2"] = { type = "Model", model = "models/items/combine_rifle_ammo01.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(-0.066, -2.764, 0.05), angle = Angle(-89.997, 90.067, 0), size = Vector(0.5, 0.503, 0.7), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bonemerge"] = { type = "Model", model = "models/weapons/c_smg1.mdl", bone = "ValveBiped.base", rel = "", pos = Vector(0.02, -2.802, -4.409), angle = Angle(-0.006, 0.01, 89.986), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bonemerge clip 1"] = { type = "ClipPlane", bone = "ValveBiped.base", rel = "bonemerge", pos = Vector(0, 0.04, 0.48), angle = Angle(0, 0, 0)},
	["bonemerge clip 1+"] = { type = "ClipPlane", bone = "ValveBiped.base", rel = "bonemerge", pos = Vector(-0.03, -14.54, 0.94), angle = Angle(0, 0, 90)},
	["front"] = { type = "Model", model = "models/props_junk/metalgascan.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(-0.381, 1.915, 0), angle = Angle(-90, -90, 0), size = Vector(0.214, 0.16, 0.497), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["frontside"] = { type = "Model", model = "models/Items/car_battery01.mdl", bone = "ValveBiped.base", rel = "front", pos = Vector(0.15, -0.5, -1), angle = Angle(0, -90, -90), size = Vector(0.2, 0.497, 0.2), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["holder"] = { type = "Model", model = "models/props_lab/reciever01b.mdl", bone = "ValveBiped.base", rel = "sightholder", pos = Vector(0.3, 0, -1.3), angle = Angle(0, 90, -90), size = Vector(0.107, 0.107, 0.107), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["scope"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.base", rel = "holder", pos = Vector(0, 0.14, -1.14), angle = Angle(0, 90, 0), size = Vector(0.04, 0.02, 0.02), color = Color(36, 36, 36, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/galvanizedmetal", skin = 0, bodygroup = {} },
	["scopeglass"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.base", rel = "scope", pos = Vector(-2, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.09, 0.09, 0.09), color = Color(153, 153, 153, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/Items/combine_rifle_cartridge01.mdl", bone = "ValveBiped.Bip01", rel = "front", pos = Vector(0, -0.7, 2.325), angle = Angle(82.987, 90, -180), size = Vector(0.302, 0.302, 0.302), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sightholder"] = { type = "Model", model = "models/props_lab/tpswitch.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(1.119, -8.16, 0), angle = Angle(0, 0, -90), size = Vector(0.107, 0.056, 0.237), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock"] = { type = "Model", model = "models/props_vehicles/carparts_door01a.mdl", bone = "ValveBiped.base", rel = "underside", pos = Vector(-0.12, 6.99, -0.36), angle = Angle(0, 0, -180), size = Vector(0.08, 0.08, 0.16), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["underside"] = { type = "Model", model = "models/props_trainstation/train005.mdl", bone = "ValveBiped.base", rel = "body", pos = Vector(0, -16.057, 0), angle = Angle(-90, 180, 0), size = Vector(0.03, 0.03, 0.03), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.WElements = {
	["back"] = { type = "Model", model = "models/props_lab/kennel_physics.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(-1.78, -8.5, 0), angle = Angle(0, -90, -90), size = Vector(0.043, 0.05, 0.08), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["barrel"] = { type = "Model", model = "models/props_rooftop/roof_vent002.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "front", pos = Vector(0, -0.53, 5.68), angle = Angle(0, 0, 0), size = Vector(0.125, 0.125, 0.125), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["body"] = { type = "Model", model = "models/props_lab/reciever01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(5.602, 1.493, -5.38), angle = Angle(-78.821, -160.011, 109.639), size = Vector(0.237, 0.756, 0.172), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["body2"] = { type = "Model", model = "models/items/combine_rifle_ammo01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0, 0, 0), angle = Angle(-90, 90, 0), size = Vector(0.5, 0.503, 0.7), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["bonemerge"] = { type = "Model", model = "models/weapons/w_smg1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["front"] = { type = "Model", model = "models/props_junk/metalgascan.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(-0.3, 4.675, 0), angle = Angle(-90, 0, 90), size = Vector(0.214, 0.16, 0.497), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["frontside"] = { type = "Model", model = "models/Items/car_battery01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "front", pos = Vector(0.15, -0.5, -1), angle = Angle(0, -90, -90), size = Vector(0.2, 0.497, 0.2), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["holder"] = { type = "Model", model = "models/props_lab/reciever01b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sightholder", pos = Vector(0.64, 0, -1.71), angle = Angle(0, 90, -90), size = Vector(0.107, 0.107, 0.107), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["scope"] = { type = "Model", model = "models/props_pipes/concrete_pipe001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "holder", pos = Vector(0.04, 0.3, -0.78), angle = Angle(0, 90, 0), size = Vector(0.04, 0.02, 0.02), color = Color(42, 42, 42, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/customs/galvanizedmetal", skin = 0, bodygroup = {} },
	["scopeglass"] = { type = "Model", model = "models/props_c17/clock01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "scope", pos = Vector(-1.76, 0, 0), angle = Angle(90, 0, 0), size = Vector(0.1, 0.1, 0.1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/sg/glass", skin = 0, bodygroup = {} },
	["sight"] = { type = "Model", model = "models/Items/combine_rifle_cartridge01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0.4, 7, 0), angle = Angle(0, -82.987, -90), size = Vector(0.302, 0.302, 0.302), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["sightholder"] = { type = "Model", model = "models/props_lab/tpswitch.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(1.2, -5.4, 0), angle = Angle(0, 0, -90), size = Vector(0.107, 0.056, 0.237), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["stock"] = { type = "Model", model = "models/props_vehicles/carparts_door01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "underside", pos = Vector(0, 8.247, 0), angle = Angle(0, 0, -180), size = Vector(0.08, 0.08, 0.16), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
	["underside"] = { type = "Model", model = "models/props_trainstation/train005.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body", pos = Vector(0.18, -7.238, 0.04), angle = Angle(-90, 0, 180), size = Vector(0.03, 0.037, 0.03), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} }
}

SWEP.ViewModelBoneMods = {}
