AddCSLuaFile()

SWEP.Base = "weapon_base"

SWEP.RenderGroup = RENDERGROUP_BOTH

SWEP.UseHands = true
SWEP.ViewModel = Model("models/weapons/c_crossbow.mdl")
SWEP.WorldModel = Model("models/weapons/w_crossbow.mdl")

SWEP.Spawnable = true

if CLIENT then
	SWEP.VElements = {
		["Emitter"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Crossbow_base", rel = "body mid", pos = Vector(-2.967, -12.819, 1.052), angle = Angle(180, -90, 90), size = Vector(0.13, 0.13, 0.13), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["Scope"] = { type = "Model", model = "models/props_phx/trains/wheel_base.mdl", bone = "ValveBiped.Crossbow_base", rel = "body mid", pos = Vector(6.7, 0.8, 1.565), angle = Angle(90, 0, 0), size = Vector(0.021, 0.1, 0.08), color = Color(76, 71, 50, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["barrel"] = { type = "Model", model = "models/props_mining/pipe_goopit01.mdl", bone = "ValveBiped.Crossbow_base", rel = "body mid", pos = Vector(0.75, -10.8, 1), angle = Angle(0, 90, 0), size = Vector(0.037, 0.008, 0.008), color = Color(97, 97, 97, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["barrel connect"] = { type = "Model", model = "models/props_c17/FurnitureFridge001a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "wood length", pos = Vector(-1.98, 0.028, 25.13), angle = Angle(-90, 180, 0), size = Vector(0.019, 0.04, 0.033), color = Color(42, 38, 38, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["barrel connect connect"] = { type = "Model", model = "models/props_c17/canister01a.mdl", bone = "ValveBiped.Crossbow_base", rel = "barrel connect", pos = Vector(1.35, 0.034, -1.35), angle = Angle(-90, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(95, 95, 95, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["barrel stabilizer length"] = { type = "Model", model = "models/hunter/blocks/cube025x150x025.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "wood length", pos = Vector(-2.3, 0.424, 14.033), angle = Angle(0, 0, -90), size = Vector(0.03, 0.2, 0.07), color = Color(31, 27, 19, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
		["body back"] = { type = "Model", model = "models/props_lab/powerbox03a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "body mid", pos = Vector(1.962, 4.377, 1.039), angle = Angle(180, 180, 90), size = Vector(0.1, 0.16, 0.4), color = Color(99, 90, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["body mid"] = { type = "Model", model = "models/props/de_prodigy/ammo_can_02.mdl", bone = "ValveBiped.Crossbow_base", rel = "", pos = Vector(-1.152, -0.741, 0.711), angle = Angle(0, 90, 90), size = Vector(0.23, 0.23, 0.23), color = Color(70, 77, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["body top"] = { type = "Model", model = "models/props_wasteland/tram_leverbase01.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "body mid", pos = Vector(1.996, -2.627, 0.97), angle = Angle(180, 90, 90), size = Vector(0.3, 0.13, 0.13), color = Color(99, 90, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["clip main"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "main", pos = Vector(-0.309, -0.797, -4.553), angle = Angle(0, 0, 86.228)},
		["clip main 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "main", pos = Vector(-0.185, 0.758, 0.327), angle = Angle(0, 0, -64.671)},
		["grip"] = { type = "Model", model = "models/weapons/w_snip_awp.mdl", bone = "ValveBiped.Crossbow_base", rel = "body mid", pos = Vector(-8.676, -7.462, 0.728), angle = Angle(0, 90, 90), size = Vector(0.98, 0.9, 0.9), color = Color(201, 169, 100, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props/cs_office/table_meeting", skin = 0, bodygroup = {} },
		["grip 2 clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "metal grip", pos = Vector(0.036, -0.009, 3.29), angle = Angle(0, 0, 0)},
		["grip 2 clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "metal grip", pos = Vector(-0.38, -0.06, 0.27), angle = Angle(-70.06, -180, -180)},
		["grip 2 clip 2+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "grip 2++", pos = Vector(-0.38, -0.06, 0.27), angle = Angle(70.056, 0, 0)},
		["grip 2 clip 3"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "grip 2+", pos = Vector(-0.119, 0.079, 3.365), angle = Angle(0, -180, 180)},
		["grip 2 clip 3+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "grip 2++", pos = Vector(-0.039, -0.019, 3.29), angle = Angle(-2.156, 0, 0)},
		["grip 2 clip 4"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "grip", pos = Vector(-12.102, 1.837, 7.065), angle = Angle(0, -180, -180)},
		["grip 2 clip 5"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "grip 2+", pos = Vector(1.032, 0.176, 3.665), angle = Angle(-97.006, 0, 180)},
		["grip 2+"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Crossbow_base", rel = "metal grip", pos = Vector(0, 0, 0.002), angle = Angle(0, 0, 0), size = Vector(1, 1.5, 1), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["grip 2++"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Crossbow_base", rel = "metal grip", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(1, 1.5, 1), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["grip clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "grip", pos = Vector(-9.999, 2.082, 5.183), angle = Angle(79.76, 0, 0)},
		["main"] = { type = "Model", model = "models/weapons/c_crossbow.mdl", bone = "ValveBiped.Crossbow_base", rel = "", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(53, 53, 53, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["metal grip"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Crossbow_base", rel = "grip", pos = Vector(-9.263, -0.191, 1.712), angle = Angle(0, 0, 0), size = Vector(1, 1.5, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope capture"] = { type = "Model", model = "models/maxofs2d/camera.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Scope", pos = Vector(-0.874, -4.403, 4.435), angle = Angle(180, -90, 0), size = Vector(0.3, 0.3, 0.3), color = Color(136, 136, 136, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope capture clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "scope capture", pos = Vector(0.214, -0.01, 0.167), angle = Angle(-90, 0, 0)},
		["scope capture clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "scope capture", pos = Vector(0.1, 0.476, 0.347), angle = Angle(-90, 90, 0)},
		["scope cover"] = { type = "Model", model = "models/props_combine/combine_bridge_b.mdl", bone = "ValveBiped.Crossbow_base", rel = "Scope", pos = Vector(-0.557, 15, 0.29), angle = Angle(0, -90, 0), size = Vector(0.035, 0.012, 0.02), color = Color(57, 50, 37, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope detail"] = { type = "Model", model = "models/props_lab/reciever01a.mdl", bone = "ValveBiped.Crossbow_base", rel = "Scope", pos = Vector(-1.129, 0.958, 4.066), angle = Angle(-3.5, 0, 0), size = Vector(0.24, 0.24, 0.24), color = Color(125, 118, 111, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope detail clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "scope detail", pos = Vector(0.936, 0.179, 0.074), angle = Angle(-77.605, 0, 0)},
		["scope front"] = { type = "Model", model = "models/props_lab/powerbox03a.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Scope", pos = Vector(-0.588, -3.5, 4.1), angle = Angle(-90, 0, 0), size = Vector(0.5, 0.33, 0.33), color = Color(42, 42, 36, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/grey_steel", skin = 0, bodygroup = {} },
		["scope view"] = { type = "Model", model = "models/tools/camera/camera.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "Scope", pos = Vector(-2.973, 3.223, 6.49), angle = Angle(-45, 90, 180), size = Vector(0.5, 0.5, 0.5), color = Color(227, 227, 227, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope view clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "scope view", pos = Vector(0.039, -1.543, 1.313), angle = Angle(0, 0, -90)},
		["scope view clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "scope view", pos = Vector(0.404, -1.203, 0.982), angle = Angle(0, 90, -45)},
		["sd clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "side detail", pos = Vector(0.628, 0.009, -0.06), angle = Angle(-90, 0, 0)},
		["sd screen"] = { type = "Model", model = "models/props_silo/silo_launchroom_monitor.mdl", bone = "ValveBiped.Crossbow_base", rel = "side detail", pos = Vector(0.961, 1.569, 0.207), angle = Angle(175, -180, 0), size = Vector(0.08, 0.09, 0.08), color = Color(102, 102, 102, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 3, bodygroup = {[2] = 2} },
		["sd screen clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "sd screen", pos = Vector(0.051, -0.019, -0.662), angle = Angle(0, 0, 0)},
		["sd screen image"] = { type = "Model", model = "models/squad/sf_plates/sf_plate1x1.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "sd screen", pos = Vector(0.931, -0.842, 0.992), angle = Angle(-95.094, 180, 0), size = Vector(0.122, 0.145, 0.03), color = Color(255, 117, 117, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_silo/launchroomdisplayc", skin = 0, bodygroup = {} },
		["side 1"] = { type = "Model", model = "models/items/ammocrate_buckshot.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "body mid", pos = Vector(0, 0, 2.013), angle = Angle(0, 0, 0), size = Vector(0.1, 0.18, 0.01), color = Color(59, 66, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["side 1+"] = { type = "Model", model = "models/items/ammocrate_buckshot.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "body mid", pos = Vector(0, 0, 0), angle = Angle(0, 0, 180), size = Vector(0.1, 0.18, 0.01), color = Color(59, 66, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["side detail"] = { type = "Model", model = "models/props_lab/reciever01b.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "stock outer", pos = Vector(0.021, 0.759, -0.76), angle = Angle(0, 90, -90), size = Vector(0.3, 0.4, 0.3), color = Color(140, 139, 139, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["silencer"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "ValveBiped.Crossbow_base", rel = "barrel", pos = Vector(15.768, 0.009, 0.061), angle = Angle(90, 0, 0), size = Vector(0.2, 0.2, 0.5), color = Color(48, 46, 39, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
		["silencer back"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_Spine4", rel = "silencer", pos = Vector(0, 0.01, 5.27), angle = Angle(0, -90, 180), size = Vector(0.035, 0.035, 0.08), color = Color(48, 46, 39, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "rubber", skin = 0, bodygroup = {} },
		["stock back cheekrest"] = { type = "Model", model = "models/props_interiors/refrigeratorDoor01a.mdl", bone = "ValveBiped.Crossbow_base", rel = "wood length", pos = Vector(-2.572, -0.004, -4.722), angle = Angle(0, 180, 0), size = Vector(0.11, 0.063, 0.17), color = Color(167, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["stock back part"] = { type = "Model", model = "models/props_interiors/VendingMachineSoda01a.mdl", bone = "ValveBiped.Crossbow_base", rel = "wood length", pos = Vector(-0.741, 0.341, -4.785), angle = Angle(180, 90, -180), size = Vector(0.038, 0.07, 0.1), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["stock end"] = { type = "Model", model = "models/weapons/w_snip_awp.mdl", bone = "ValveBiped.Crossbow_base", rel = "grip", pos = Vector(2.545, 0.035, -0.522), angle = Angle(0, 0, 0), size = Vector(1.085, 1.085, 1.085), color = Color(44, 44, 44, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/grey_steel", skin = 0, bodygroup = {} },
		["stock end clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_Spine4", rel = "stock end", pos = Vector(-23.825, 5.927, 5.848), angle = Angle(90, 0, 0)},
		["stock outer"] = { type = "Model", model = "models/props_lab/powerbox02a.mdl", bone = "ValveBiped.Crossbow_base", rel = "grip", pos = Vector(-18.244, -0.294, 8.7), angle = Angle(90, 0, 0), size = Vector(0.31, 0.18, 0.5), color = Color(38, 38, 38, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/grey_steel", skin = 0, bodygroup = {} },
		["wood length"] = { type = "Model", model = "models/props_silo/nucleartestcabinet.mdl", bone = "ValveBiped.Crossbow_base", rel = "body mid", pos = Vector(-1, 5.5, 1.012), angle = Angle(0, 180, 90), size = Vector(0.13, 0.076, 0.268), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} }
	}

	SWEP.WElements = {
		["Emitter"] = { type = "Model", model = "models/lamps/torch.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(-2.967, -12.819, 1.052), angle = Angle(180, -90, 90), size = Vector(0.13, 0.13, 0.13), color = Color(0, 0, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["Scope"] = { type = "Model", model = "models/props_phx/trains/wheel_base.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(6.7, 0.8, 1.565), angle = Angle(90, 0, 0), size = Vector(0.021, 0.1, 0.08), color = Color(76, 71, 50, 255), surpresslightning = false, bonemerge = false, highrender = true, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["barrel"] = { type = "Model", model = "models/props_mining/pipe_goopit01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(0.75, -10.8, 1), angle = Angle(0, 90, 0), size = Vector(0.037, 0.008, 0.008), color = Color(97, 97, 97, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["barrel connect"] = { type = "Model", model = "models/props_c17/FurnitureFridge001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "wood length", pos = Vector(-1.98, 0.028, 25.13), angle = Angle(-90, 180, 0), size = Vector(0.019, 0.04, 0.033), color = Color(42, 38, 38, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["barrel connect connect"] = { type = "Model", model = "models/props_c17/canister01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel connect", pos = Vector(1.35, 0.034, -1.35), angle = Angle(-90, 0, 0), size = Vector(0.05, 0.05, 0.05), color = Color(95, 95, 95, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["barrel stabilizer length"] = { type = "Model", model = "models/hunter/blocks/cube025x150x025.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "wood length", pos = Vector(-2.3, 0.424, 14.033), angle = Angle(0, 0, -90), size = Vector(0.03, 0.2, 0.07), color = Color(31, 27, 19, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
		["body back"] = { type = "Model", model = "models/props_lab/powerbox03a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(1.962, 4.377, 1.039), angle = Angle(180, 180, 90), size = Vector(0.1, 0.16, 0.4), color = Color(99, 90, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["body mid"] = { type = "Model", model = "models/props/de_prodigy/ammo_can_02.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(5.476, 0.175, -3.531), angle = Angle(-90.603, 5.126, 85.135), size = Vector(0.23, 0.23, 0.23), color = Color(70, 77, 89, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["body top"] = { type = "Model", model = "models/props_wasteland/tram_leverbase01.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(1.996, -2.627, 0.97), angle = Angle(180, 90, 90), size = Vector(0.3, 0.13, 0.13), color = Color(99, 90, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/gibs/metalgibs/metal_gibs", skin = 0, bodygroup = {} },
		["clip main"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "main", pos = Vector(-0.309, -0.797, -4.553), angle = Angle(0, 0, 0)},
		["clip main 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "main", pos = Vector(5.319, 1.294, -5.317), angle = Angle(-86.228, 8.623, 0)},
		["grip"] = { type = "Model", model = "models/weapons/w_snip_awp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(-8.676, -7.462, 0.728), angle = Angle(0, 90, 90), size = Vector(0.98, 0.9, 0.9), color = Color(201, 169, 100, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props/cs_office/table_meeting", skin = 0, bodygroup = {} },
		["grip 2 clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "metal grip", pos = Vector(0.036, -0.009, 3.29), angle = Angle(0, 0, 0)},
		["grip 2 clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "metal grip", pos = Vector(-0.38, -0.06, 0.27), angle = Angle(-70.06, -180, -180)},
		["grip 2 clip 2+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip 2++", pos = Vector(-0.38, -0.06, 0.27), angle = Angle(70.056, 0, 0)},
		["grip 2 clip 3"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip 2+", pos = Vector(-0.119, 0.079, 3.365), angle = Angle(0, -180, 180)},
		["grip 2 clip 3+"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip 2++", pos = Vector(-0.039, -0.019, 3.29), angle = Angle(-2.156, 0, 0)},
		["grip 2 clip 4"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(-12.102, 1.837, 7.065), angle = Angle(0, -180, -180)},
		["grip 2 clip 5"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip 2+", pos = Vector(1.032, 0.176, 3.665), angle = Angle(-97.006, 0, 180)},
		["grip 2+"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "metal grip", pos = Vector(0, 0, 0.002), angle = Angle(0, 0, 0), size = Vector(1, 1.5, 1), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["grip 2++"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "metal grip", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(1, 1.5, 1), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["grip clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(-9.999, 2.082, 5.183), angle = Angle(79.76, 0, 0)},
		["main"] = { type = "Model", model = "models/weapons/w_crossbow.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "", pos = Vector(0, 0, 0), angle = Angle(0, 0, 0), size = Vector(0.5, 0.5, 0.5), color = Color(53, 53, 53, 255), surpresslightning = false, bonemerge = true, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["metal grip"] = { type = "Model", model = "models/weapons/w_pist_usp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(-9.263, -0.191, 1.712), angle = Angle(0, 0, 0), size = Vector(1, 1.5, 1), color = Color(255, 255, 255, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope capture"] = { type = "Model", model = "models/maxofs2d/camera.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Scope", pos = Vector(-0.874, -4.403, 4.435), angle = Angle(180, -90, 0), size = Vector(0.3, 0.3, 0.3), color = Color(136, 136, 136, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope capture clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "scope capture", pos = Vector(0.214, -0.01, 0.167), angle = Angle(-90, 0, 0)},
		["scope capture clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "scope capture", pos = Vector(0.1, 0.476, 0.347), angle = Angle(-90, 90, 0)},
		["scope cover"] = { type = "Model", model = "models/props_combine/combine_bridge_b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Scope", pos = Vector(-0.557, 15, 0.29), angle = Angle(0, -90, 0), size = Vector(0.035, 0.012, 0.02), color = Color(57, 50, 37, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope detail"] = { type = "Model", model = "models/props_lab/reciever01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Scope", pos = Vector(-1.129, 0.958, 4.066), angle = Angle(-3.5, 0, 0), size = Vector(0.24, 0.24, 0.24), color = Color(125, 118, 111, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope detail clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "scope detail", pos = Vector(0.936, 0.179, 0.074), angle = Angle(-77.605, 0, 0)},
		["scope front"] = { type = "Model", model = "models/props_lab/powerbox03a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Scope", pos = Vector(-0.588, -3.5, 4.1), angle = Angle(-90, 0, 0), size = Vector(0.5, 0.33, 0.33), color = Color(42, 42, 36, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/grey_steel", skin = 0, bodygroup = {} },
		["scope view"] = { type = "Model", model = "models/tools/camera/camera.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "Scope", pos = Vector(-2.973, 3.223, 6.49), angle = Angle(-45, 90, 180), size = Vector(0.5, 0.5, 0.5), color = Color(227, 227, 227, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["scope view clip 1"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view", pos = Vector(0.039, -1.543, 1.313), angle = Angle(0, 0, -90)},
		["scope view clip 2"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "scope view", pos = Vector(0.404, -1.203, 0.982), angle = Angle(0, 90, -45)},
		["sd clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "side detail", pos = Vector(0.628, 0.009, -0.06), angle = Angle(-90, 0, 0)},
		["sd screen"] = { type = "Model", model = "models/props_silo/silo_launchroom_monitor.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "side detail", pos = Vector(0.961, 1.569, 0.207), angle = Angle(175, -180, 0), size = Vector(0.08, 0.09, 0.08), color = Color(102, 102, 102, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 3, bodygroup = {[2] = 2} },
		["sd screen clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "sd screen", pos = Vector(0.051, -0.019, -0.662), angle = Angle(0, 0, 0)},
		["sd screen image"] = { type = "Model", model = "models/squad/sf_plates/sf_plate1x1.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "sd screen", pos = Vector(0.931, -0.842, 0.992), angle = Angle(-95.094, 180, 0), size = Vector(0.122, 0.145, 0.03), color = Color(255, 117, 117, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/props_silo/launchroomdisplayc", skin = 0, bodygroup = {} },
		["side 1"] = { type = "Model", model = "models/items/ammocrate_buckshot.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(0, 0, 2.013), angle = Angle(0, 0, 0), size = Vector(0.1, 0.18, 0.01), color = Color(59, 66, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["side 1+"] = { type = "Model", model = "models/items/ammocrate_buckshot.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(0, 0, 0), angle = Angle(0, 0, 180), size = Vector(0.1, 0.18, 0.01), color = Color(59, 66, 78, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["side detail"] = { type = "Model", model = "models/props_lab/reciever01b.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "stock outer", pos = Vector(0.021, 0.759, -0.76), angle = Angle(0, 90, -90), size = Vector(0.3, 0.4, 0.3), color = Color(140, 139, 139, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "", skin = 0, bodygroup = {} },
		["silencer"] = { type = "Model", model = "models/props_junk/propane_tank001a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "barrel", pos = Vector(15.768, 0.009, 0.061), angle = Angle(90, 0, 0), size = Vector(0.2, 0.2, 0.5), color = Color(48, 46, 39, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "metal2", skin = 0, bodygroup = {} },
		["silencer back"] = { type = "Model", model = "models/props_wasteland/laundry_basket001.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "silencer", pos = Vector(0, 0.01, 5.27), angle = Angle(0, -90, 180), size = Vector(0.035, 0.035, 0.08), color = Color(48, 46, 39, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "rubber", skin = 0, bodygroup = {} },
		["stock back cheekrest"] = { type = "Model", model = "models/props_interiors/refrigeratorDoor01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "wood length", pos = Vector(-2.572, -0.004, -4.722), angle = Angle(0, 180, 0), size = Vector(0.11, 0.063, 0.17), color = Color(167, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["stock back part"] = { type = "Model", model = "models/props_interiors/VendingMachineSoda01a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "wood length", pos = Vector(-0.741, 0.341, -4.785), angle = Angle(180, 90, -180), size = Vector(0.038, 0.07, 0.1), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} },
		["stock end"] = { type = "Model", model = "models/weapons/w_snip_awp.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(2.545, 0.035, -0.522), angle = Angle(0, 0, 0), size = Vector(1.085, 1.085, 1.085), color = Color(44, 44, 44, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/grey_steel", skin = 0, bodygroup = {} },
		["stock end clip"] = { type = "ClipPlane", bone = "ValveBiped.Bip01_R_Hand", rel = "stock end", pos = Vector(-23.825, 5.927, 5.848), angle = Angle(90, 0, 0)},
		["stock outer"] = { type = "Model", model = "models/props_lab/powerbox02a.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "grip", pos = Vector(-18.244, -0.294, 8.7), angle = Angle(90, 0, 0), size = Vector(0.31, 0.18, 0.5), color = Color(38, 38, 38, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "phoenix_storms/grey_steel", skin = 0, bodygroup = {} },
		["wood length"] = { type = "Model", model = "models/props_silo/nucleartestcabinet.mdl", bone = "ValveBiped.Bip01_R_Hand", rel = "body mid", pos = Vector(-1, 5.5, 1.012), angle = Angle(0, 180, 90), size = Vector(0.13, 0.076, 0.268), color = Color(163, 103, 0, 255), surpresslightning = false, bonemerge = false, highrender = false, nocull = false, material = "models/sg/wood/offdesktop", skin = 0, bodygroup = {} }
	}

	SWEP.ViewModelBoneMods = {
		["ValveBiped.Bip01_L_Clavicle"] = { pos = Vector(-1.437, 0.359, 8.623) },
		["ValveBiped.bolt"] = { hide = true }
	}

	SWEP.ShowViewModel = false
	SWEP.ShowWorldModel = false
end

include("cl_sck.lua")

function SWEP:Initialize()
	if CLIENT then
		self:InitSCK()
	end
end

function SWEP:OnReloaded()
	if CLIENT then
		self:InitSCK()
	end
end
